<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AppSistema.Instalador</RootNamespace>
    <AssemblyName>AppSistema.Instalador</AssemblyName>
    <StartupObject>AppSistema.Instalador.Programa</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppSistema.Datos\AppSistema.Datos.vbproj" />
  </ItemGroup>

</Project>
