-- Esquema base v0.3 portado de SQLite a PostgreSQL (generado y revisado).



CREATE TABLE empresa (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo TEXT NOT NULL UNIQUE, nombre TEXT NOT NULL, identificacion_fiscal TEXT, moneda TEXT NOT NULL DEFAULT 'PEN', activo BIGINT NOT NULL DEFAULT 1 CHECK(activo IN (0,1)));

CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  nombre TEXT NOT NULL,
  login TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  activo BIGINT NOT NULL DEFAULT 1 CHECK(activo IN (0,1)),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,login)
);

CREATE INDEX ix_usuario_empresa ON usuario(empresa_id);

CREATE TABLE rol (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_rol_empresa ON rol(empresa_id);

CREATE TABLE permiso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  descripcion TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_permiso_empresa ON permiso(empresa_id);

CREATE TABLE rol_permiso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  rol_id BIGINT NOT NULL,
  permiso_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,rol_id) REFERENCES rol(empresa_id,id),
  FOREIGN KEY(empresa_id,permiso_id) REFERENCES permiso(empresa_id,id),
  UNIQUE(empresa_id,rol_id,permiso_id)
);

CREATE INDEX ix_rol_permiso_empresa ON rol_permiso(empresa_id);

CREATE TABLE operacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  ubicacion TEXT,
  zona TEXT,
  activo BIGINT NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_operacion_empresa ON operacion(empresa_id);

CREATE TABLE usuario_operacion_rol (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  usuario_id BIGINT NOT NULL,
  operacion_id BIGINT NOT NULL,
  rol_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id),
  FOREIGN KEY(empresa_id,operacion_id) REFERENCES operacion(empresa_id,id),
  FOREIGN KEY(empresa_id,rol_id) REFERENCES rol(empresa_id,id),
  UNIQUE(empresa_id,usuario_id,operacion_id,rol_id)
);

CREATE INDEX ix_usuario_operacion_rol_empresa ON usuario_operacion_rol(empresa_id);

CREATE TABLE almacen (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  operacion_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  activo BIGINT NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,operacion_id) REFERENCES operacion(empresa_id,id),
  UNIQUE(empresa_id,operacion_id,codigo)
);

CREATE INDEX ix_almacen_empresa ON almacen(empresa_id);

CREATE TABLE unidad_medida (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  dimension TEXT NOT NULL CHECK(dimension IN ('masa','volumen','conteo')),
  decimales BIGINT NOT NULL DEFAULT 3 CHECK(decimales BETWEEN 0 AND 6),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_unidad_medida_empresa ON unidad_medida(empresa_id);

CREATE TABLE categoria_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_categoria_producto_empresa ON categoria_producto(empresa_id);

CREATE TABLE producto_base (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  especificacion TEXT,
  unidad_base_id BIGINT NOT NULL,
  categoria_id BIGINT,
  activo BIGINT NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,unidad_base_id) REFERENCES unidad_medida(empresa_id,id),
  FOREIGN KEY(empresa_id,categoria_id) REFERENCES categoria_producto(empresa_id,id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_producto_base_empresa ON producto_base(empresa_id);

CREATE TABLE marca (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  nombre TEXT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,nombre)
);

CREATE INDEX ix_marca_empresa ON marca(empresa_id);

CREATE TABLE variante_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  producto_base_id BIGINT NOT NULL,
  marca_id BIGINT,
  codigo TEXT NOT NULL,
  descripcion_comercial TEXT NOT NULL,
  tipo_envase TEXT NOT NULL,
  contenido_base_por_envase_u6 BIGINT NOT NULL CHECK(contenido_base_por_envase_u6>0),
  activo BIGINT NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,producto_base_id) REFERENCES producto_base(empresa_id,id),
  FOREIGN KEY(empresa_id,marca_id) REFERENCES marca(empresa_id,id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_variante_producto_empresa ON variante_producto(empresa_id);

CREATE TABLE empaque_compra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  variante_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  envases_por_empaque BIGINT NOT NULL CHECK(envases_por_empaque>0),
  minimo_empaques BIGINT NOT NULL DEFAULT 1 CHECK(minimo_empaques>0),
  multiplo_empaques BIGINT NOT NULL DEFAULT 1 CHECK(multiplo_empaques>0),
  activo BIGINT NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,variante_id) REFERENCES variante_producto(empresa_id,id),
  UNIQUE(empresa_id,variante_id,codigo)
);

CREATE INDEX ix_empaque_compra_empresa ON empaque_compra(empresa_id);

CREATE TABLE proveedor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  identificacion_fiscal TEXT,
  contacto TEXT,
  correo TEXT,
  telefono TEXT,
  es_caja_chica BIGINT NOT NULL DEFAULT 0,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_proveedor_empresa ON proveedor(empresa_id);

CREATE TABLE proveedor_empaque (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  proveedor_id BIGINT NOT NULL,
  empaque_id BIGINT NOT NULL,
  plazo_entrega_dias BIGINT NOT NULL DEFAULT 0 CHECK(plazo_entrega_dias>=0),
  activo BIGINT NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,proveedor_id) REFERENCES proveedor(empresa_id,id),
  FOREIGN KEY(empresa_id,empaque_id) REFERENCES empaque_compra(empresa_id,id),
  UNIQUE(empresa_id,proveedor_id,empaque_id)
);

CREATE INDEX ix_proveedor_empaque_empresa ON proveedor_empaque(empresa_id);

CREATE TABLE precio_compra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  proveedor_empaque_id BIGINT NOT NULL,
  fecha_desde DATE NOT NULL,
  fecha_hasta DATE,
  moneda TEXT NOT NULL,
  precio_empaque_u6 BIGINT NOT NULL CHECK(precio_empaque_u6>=0),
  incluye_impuesto BIGINT NOT NULL DEFAULT 0,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,proveedor_empaque_id) REFERENCES proveedor_empaque(empresa_id,id),
  CHECK(fecha_hasta IS NULL OR fecha_hasta>=fecha_desde)
);

CREATE INDEX ix_precio_compra_empresa ON precio_compra(empresa_id);

CREATE TABLE politica_abastecimiento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  almacen_id BIGINT NOT NULL,
  producto_base_id BIGINT NOT NULL,
  reserva_base_u6 BIGINT NOT NULL DEFAULT 0 CHECK(reserva_base_u6>=0),
  cobertura_dias BIGINT NOT NULL DEFAULT 0 CHECK(cobertura_dias>=0),
  plazo_entrega_dias BIGINT NOT NULL DEFAULT 0 CHECK(plazo_entrega_dias>=0),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,almacen_id) REFERENCES almacen(empresa_id,id),
  FOREIGN KEY(empresa_id,producto_base_id) REFERENCES producto_base(empresa_id,id),
  UNIQUE(empresa_id,almacen_id,producto_base_id)
);

CREATE INDEX ix_politica_abastecimiento_empresa ON politica_abastecimiento(empresa_id);

CREATE TABLE servicio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_servicio_empresa ON servicio(empresa_id);

CREATE TABLE regimen (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_regimen_empresa ON regimen(empresa_id);

CREATE TABLE estructura_servicio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  servicio_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  orden BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,servicio_id) REFERENCES servicio(empresa_id,id),
  UNIQUE(empresa_id,servicio_id,codigo)
);

CREATE INDEX ix_estructura_servicio_empresa ON estructura_servicio(empresa_id);

CREATE TABLE operacion_servicio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  operacion_id BIGINT NOT NULL,
  servicio_id BIGINT NOT NULL,
  regimen_id BIGINT NOT NULL,
  costo_objetivo_racion_u6 BIGINT CHECK(costo_objetivo_racion_u6>=0),
  food_cost_objetivo_bp BIGINT CHECK(food_cost_objetivo_bp BETWEEN 0 AND 10000),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,operacion_id) REFERENCES operacion(empresa_id,id),
  FOREIGN KEY(empresa_id,servicio_id) REFERENCES servicio(empresa_id,id),
  FOREIGN KEY(empresa_id,regimen_id) REFERENCES regimen(empresa_id,id),
  UNIQUE(empresa_id,operacion_id,servicio_id,regimen_id)
);

CREATE INDEX ix_operacion_servicio_empresa ON operacion_servicio(empresa_id);

CREATE TABLE receta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  categoria TEXT,
  activo BIGINT NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_receta_empresa ON receta(empresa_id);

CREATE TABLE receta_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  receta_id BIGINT NOT NULL,
  version BIGINT NOT NULL CHECK(version>0),
  rendimiento_raciones_u6 BIGINT NOT NULL CHECK(rendimiento_raciones_u6>0),
  instrucciones TEXT,
  estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','aprobada','retirada')),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,receta_id) REFERENCES receta(empresa_id,id),
  UNIQUE(empresa_id,receta_id,version)
);

CREATE INDEX ix_receta_version_empresa ON receta_version(empresa_id);

CREATE TABLE receta_ingrediente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  receta_version_id BIGINT NOT NULL,
  producto_base_id BIGINT NOT NULL,
  cantidad_base_bruta_u6 BIGINT NOT NULL CHECK(cantidad_base_bruta_u6>0),
  cantidad_base_neta_u6 BIGINT CHECK(cantidad_base_neta_u6>=0),
  orden BIGINT NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,receta_version_id) REFERENCES receta_version(empresa_id,id),
  FOREIGN KEY(empresa_id,producto_base_id) REFERENCES producto_base(empresa_id,id),
  CHECK(cantidad_base_neta_u6 IS NULL OR cantidad_base_neta_u6<=cantidad_base_bruta_u6)
);

CREATE INDEX ix_receta_ingrediente_empresa ON receta_ingrediente(empresa_id);

CREATE TABLE ingrediente_variante_permitida (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  ingrediente_id BIGINT NOT NULL,
  variante_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,ingrediente_id) REFERENCES receta_ingrediente(empresa_id,id),
  FOREIGN KEY(empresa_id,variante_id) REFERENCES variante_producto(empresa_id,id),
  UNIQUE(empresa_id,ingrediente_id,variante_id)
);

CREATE INDEX ix_ingrediente_variante_permitida_empresa ON ingrediente_variante_permitida(empresa_id);

CREATE TABLE minuta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  operacion_servicio_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  tipo TEXT NOT NULL CHECK(tipo IN ('teorica','real')),
  minuta_origen_id BIGINT,
  comensales BIGINT NOT NULL CHECK(comensales>=0),
  estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','aprobada','cerrada')),
  usuario_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,operacion_servicio_id) REFERENCES operacion_servicio(empresa_id,id),
  FOREIGN KEY(empresa_id,minuta_origen_id) REFERENCES minuta(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id),
  UNIQUE(empresa_id,operacion_servicio_id,fecha,tipo)
);

CREATE INDEX ix_minuta_empresa ON minuta(empresa_id);

CREATE TABLE minuta_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  minuta_id BIGINT NOT NULL,
  estructura_id BIGINT NOT NULL,
  receta_version_id BIGINT NOT NULL,
  raciones BIGINT NOT NULL CHECK(raciones>=0),
  costo_previsto_racion_u6 BIGINT CHECK(costo_previsto_racion_u6>=0),
  fecha_costeo DATE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,minuta_id) REFERENCES minuta(empresa_id,id),
  FOREIGN KEY(empresa_id,estructura_id) REFERENCES estructura_servicio(empresa_id,id),
  FOREIGN KEY(empresa_id,receta_version_id) REFERENCES receta_version(empresa_id,id)
);

CREATE INDEX ix_minuta_detalle_empresa ON minuta_detalle(empresa_id);

CREATE TABLE minuta_estructura_fija (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  minuta_id BIGINT NOT NULL,
  producto_base_id BIGINT NOT NULL,
  cantidad_base_u6 BIGINT NOT NULL CHECK(cantidad_base_u6>=0),
  costo_previsto_unitario_u6 BIGINT CHECK(costo_previsto_unitario_u6>=0),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,minuta_id) REFERENCES minuta(empresa_id,id),
  FOREIGN KEY(empresa_id,producto_base_id) REFERENCES producto_base(empresa_id,id)
);

CREATE INDEX ix_minuta_estructura_fija_empresa ON minuta_estructura_fija(empresa_id);

CREATE TABLE costeo_ingrediente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  minuta_detalle_id BIGINT NOT NULL,
  ingrediente_id BIGINT NOT NULL,
  costo_unitario_base_u6 BIGINT NOT NULL CHECK(costo_unitario_base_u6>=0),
  fuente_precio TEXT NOT NULL,
  fecha_precio DATE NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,minuta_detalle_id) REFERENCES minuta_detalle(empresa_id,id),
  FOREIGN KEY(empresa_id,ingrediente_id) REFERENCES receta_ingrediente(empresa_id,id),
  UNIQUE(empresa_id,minuta_detalle_id,ingrediente_id)
);

CREATE INDEX ix_costeo_ingrediente_empresa ON costeo_ingrediente(empresa_id);

CREATE TABLE prevision (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  almacen_id BIGINT NOT NULL,
  fecha_desde DATE NOT NULL,
  fecha_hasta DATE NOT NULL,
  fecha_calculo TIMESTAMPTZ NOT NULL,
  estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','validada','reemplazada')),
  usuario_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,almacen_id) REFERENCES almacen(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id),
  CHECK(fecha_hasta>=fecha_desde)
);

CREATE INDEX ix_prevision_empresa ON prevision(empresa_id);

CREATE TABLE prevision_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  prevision_id BIGINT NOT NULL,
  producto_base_id BIGINT NOT NULL,
  necesidad_menu_u6 BIGINT NOT NULL CHECK(necesidad_menu_u6>=0),
  consumo_puente_u6 BIGINT NOT NULL DEFAULT 0 CHECK(consumo_puente_u6>=0),
  stock_utilizable_u6 BIGINT NOT NULL CHECK(stock_utilizable_u6>=0),
  reserva_u6 BIGINT NOT NULL DEFAULT 0 CHECK(reserva_u6>=0),
  pendiente_recibir_u6 BIGINT NOT NULL DEFAULT 0 CHECK(pendiente_recibir_u6>=0),
  necesidad_neta_u6 BIGINT NOT NULL CHECK(necesidad_neta_u6>=0),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,prevision_id) REFERENCES prevision(empresa_id,id),
  FOREIGN KEY(empresa_id,producto_base_id) REFERENCES producto_base(empresa_id,id),
  UNIQUE(empresa_id,prevision_id,producto_base_id)
);

CREATE INDEX ix_prevision_detalle_empresa ON prevision_detalle(empresa_id);

CREATE TABLE pedido_compra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  almacen_id BIGINT NOT NULL,
  proveedor_id BIGINT NOT NULL,
  prevision_id BIGINT,
  numero TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK(tipo IN ('normal','extra','caja_chica')),
  fecha DATE NOT NULL,
  moneda TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','aprobado','enviado','parcial','recibido','anulado')),
  usuario_id BIGINT NOT NULL,
  aprobador_id BIGINT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,almacen_id) REFERENCES almacen(empresa_id,id),
  FOREIGN KEY(empresa_id,proveedor_id) REFERENCES proveedor(empresa_id,id),
  FOREIGN KEY(empresa_id,prevision_id) REFERENCES prevision(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id),
  FOREIGN KEY(empresa_id,aprobador_id) REFERENCES usuario(empresa_id,id),
  UNIQUE(empresa_id,numero)
);

CREATE INDEX ix_pedido_compra_empresa ON pedido_compra(empresa_id);

CREATE TABLE pedido_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  pedido_id BIGINT NOT NULL,
  empaque_id BIGINT NOT NULL,
  cantidad_empaques BIGINT NOT NULL CHECK(cantidad_empaques>0),
  factor_base_por_empaque_u6 BIGINT NOT NULL CHECK(factor_base_por_empaque_u6>0),
  cantidad_base_u6 BIGINT NOT NULL CHECK(cantidad_base_u6>0),
  precio_empaque_u6 BIGINT NOT NULL CHECK(precio_empaque_u6>=0),
  fecha_entrega DATE NOT NULL,
  prevision_detalle_id BIGINT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,pedido_id) REFERENCES pedido_compra(empresa_id,id),
  FOREIGN KEY(empresa_id,empaque_id) REFERENCES empaque_compra(empresa_id,id),
  FOREIGN KEY(empresa_id,prevision_detalle_id) REFERENCES prevision_detalle(empresa_id,id),
  CHECK(cantidad_base_u6=cantidad_empaques*factor_base_por_empaque_u6)
);

CREATE INDEX ix_pedido_detalle_empresa ON pedido_detalle(empresa_id);

CREATE TABLE recepcion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  almacen_id BIGINT NOT NULL,
  proveedor_id BIGINT NOT NULL,
  pedido_id BIGINT,
  numero TEXT NOT NULL,
  tipo_documento TEXT NOT NULL,
  numero_documento TEXT NOT NULL,
  fecha_documento DATE NOT NULL,
  fecha_recepcion DATE NOT NULL,
  moneda TEXT NOT NULL,
  tipo_ingreso TEXT NOT NULL CHECK(tipo_ingreso IN ('compra','caja_chica','traspaso','apertura')),
  estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','confirmada','anulada')),
  usuario_id BIGINT NOT NULL,
  observacion TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,almacen_id) REFERENCES almacen(empresa_id,id),
  FOREIGN KEY(empresa_id,proveedor_id) REFERENCES proveedor(empresa_id,id),
  FOREIGN KEY(empresa_id,pedido_id) REFERENCES pedido_compra(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id),
  UNIQUE(empresa_id,numero)
);

CREATE INDEX ix_recepcion_empresa ON recepcion(empresa_id);

CREATE TABLE recepcion_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  recepcion_id BIGINT NOT NULL,
  variante_id BIGINT NOT NULL,
  pedido_detalle_id BIGINT,
  empaque_id BIGINT,
  unidad_recibida TEXT NOT NULL,
  cantidad_recibida_u6 BIGINT NOT NULL CHECK(cantidad_recibida_u6>0),
  factor_conversion_u6 BIGINT NOT NULL CHECK(factor_conversion_u6>0),
  cantidad_base_u6 BIGINT NOT NULL CHECK(cantidad_base_u6>0),
  precio_unidad_recibida_u6 BIGINT NOT NULL CHECK(precio_unidad_recibida_u6>=0),
  descuento_u6 BIGINT NOT NULL DEFAULT 0 CHECK(descuento_u6>=0),
  impuesto_u6 BIGINT NOT NULL DEFAULT 0 CHECK(impuesto_u6>=0),
  cargos_u6 BIGINT NOT NULL DEFAULT 0 CHECK(cargos_u6>=0),
  costo_adquisicion_u6 BIGINT NOT NULL CHECK(costo_adquisicion_u6>=0),
  costo_unitario_base_u6 BIGINT NOT NULL CHECK(costo_unitario_base_u6>=0),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,recepcion_id) REFERENCES recepcion(empresa_id,id),
  FOREIGN KEY(empresa_id,variante_id) REFERENCES variante_producto(empresa_id,id),
  FOREIGN KEY(empresa_id,pedido_detalle_id) REFERENCES pedido_detalle(empresa_id,id),
  FOREIGN KEY(empresa_id,empaque_id) REFERENCES empaque_compra(empresa_id,id)
);

CREATE INDEX ix_recepcion_detalle_empresa ON recepcion_detalle(empresa_id);

CREATE TABLE requerimiento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  almacen_id BIGINT NOT NULL,
  minuta_id BIGINT,
  operacion_servicio_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  numero TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','aprobado','atendido','anulado')),
  usuario_id BIGINT NOT NULL,
  aprobador_id BIGINT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,almacen_id) REFERENCES almacen(empresa_id,id),
  FOREIGN KEY(empresa_id,minuta_id) REFERENCES minuta(empresa_id,id),
  FOREIGN KEY(empresa_id,operacion_servicio_id) REFERENCES operacion_servicio(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id),
  FOREIGN KEY(empresa_id,aprobador_id) REFERENCES usuario(empresa_id,id),
  UNIQUE(empresa_id,numero)
);

CREATE INDEX ix_requerimiento_empresa ON requerimiento(empresa_id);

CREATE TABLE requerimiento_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  requerimiento_id BIGINT NOT NULL,
  producto_base_id BIGINT NOT NULL,
  cantidad_prevista_u6 BIGINT NOT NULL CHECK(cantidad_prevista_u6>=0),
  cantidad_solicitada_u6 BIGINT NOT NULL CHECK(cantidad_solicitada_u6>=0),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,requerimiento_id) REFERENCES requerimiento(empresa_id,id),
  FOREIGN KEY(empresa_id,producto_base_id) REFERENCES producto_base(empresa_id,id)
);

CREATE INDEX ix_requerimiento_detalle_empresa ON requerimiento_detalle(empresa_id);

CREATE TABLE documento_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  almacen_id BIGINT NOT NULL,
  almacen_destino_id BIGINT,
  requerimiento_id BIGINT,
  recepcion_id BIGINT,
  operacion_servicio_id BIGINT,
  numero TEXT NOT NULL,
  fecha DATE NOT NULL,
  tipo TEXT NOT NULL CHECK(tipo IN ('recepcion','salida_produccion','devolucion_produccion','baja','traspaso_salida','traspaso_entrada','ajuste_positivo','ajuste_negativo','apertura','reversion')),
  estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','confirmado','anulado')),
  motivo TEXT,
  usuario_id BIGINT NOT NULL,
  aprobador_id BIGINT,
  documento_origen_id BIGINT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,almacen_id) REFERENCES almacen(empresa_id,id),
  FOREIGN KEY(empresa_id,almacen_destino_id) REFERENCES almacen(empresa_id,id),
  FOREIGN KEY(empresa_id,requerimiento_id) REFERENCES requerimiento(empresa_id,id),
  FOREIGN KEY(empresa_id,recepcion_id) REFERENCES recepcion(empresa_id,id),
  FOREIGN KEY(empresa_id,operacion_servicio_id) REFERENCES operacion_servicio(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id),
  FOREIGN KEY(empresa_id,aprobador_id) REFERENCES usuario(empresa_id,id),
  FOREIGN KEY(empresa_id,documento_origen_id) REFERENCES documento_stock(empresa_id,id),
  CHECK(almacen_destino_id IS NULL OR almacen_destino_id<>almacen_id),
  UNIQUE(empresa_id,numero)
);

CREATE INDEX ix_documento_stock_empresa ON documento_stock(empresa_id);

CREATE TABLE documento_stock_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  documento_id BIGINT NOT NULL,
  variante_id BIGINT NOT NULL,
  cantidad_base_u6 BIGINT NOT NULL CHECK(cantidad_base_u6>0),
  costo_unitario_base_u6 BIGINT NOT NULL CHECK(costo_unitario_base_u6>=0),
  valor_u6 BIGINT NOT NULL CHECK(valor_u6>=0),
  recepcion_detalle_id BIGINT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,documento_id) REFERENCES documento_stock(empresa_id,id),
  FOREIGN KEY(empresa_id,variante_id) REFERENCES variante_producto(empresa_id,id),
  FOREIGN KEY(empresa_id,recepcion_detalle_id) REFERENCES recepcion_detalle(empresa_id,id)
);

CREATE INDEX ix_documento_stock_detalle_empresa ON documento_stock_detalle(empresa_id);

CREATE TABLE movimiento_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  documento_detalle_id BIGINT NOT NULL,
  almacen_id BIGINT NOT NULL,
  variante_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  secuencia BIGINT NOT NULL CHECK(secuencia>0),
  signo BIGINT NOT NULL CHECK(signo IN (-1,1)),
  cantidad_base_u6 BIGINT NOT NULL CHECK(cantidad_base_u6>0),
  costo_unitario_base_u6 BIGINT NOT NULL CHECK(costo_unitario_base_u6>=0),
  valor_u6 BIGINT NOT NULL CHECK(valor_u6>=0),
  usuario_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,documento_detalle_id) REFERENCES documento_stock_detalle(empresa_id,id),
  FOREIGN KEY(empresa_id,almacen_id) REFERENCES almacen(empresa_id,id),
  FOREIGN KEY(empresa_id,variante_id) REFERENCES variante_producto(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id),
  UNIQUE(empresa_id,documento_detalle_id),
  UNIQUE(empresa_id,almacen_id,secuencia)
);

CREATE INDEX ix_movimiento_stock_empresa ON movimiento_stock(empresa_id);

CREATE TABLE saldo_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  almacen_id BIGINT NOT NULL,
  variante_id BIGINT NOT NULL,
  cantidad_base_u6 BIGINT NOT NULL DEFAULT 0 CHECK(cantidad_base_u6>=0),
  valor_u6 BIGINT NOT NULL DEFAULT 0 CHECK(valor_u6>=0),
  version BIGINT NOT NULL DEFAULT 0,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,almacen_id) REFERENCES almacen(empresa_id,id),
  FOREIGN KEY(empresa_id,variante_id) REFERENCES variante_producto(empresa_id,id),
  UNIQUE(empresa_id,almacen_id,variante_id)
);

CREATE INDEX ix_saldo_stock_empresa ON saldo_stock(empresa_id);

CREATE TABLE produccion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  minuta_id BIGINT,
  operacion_servicio_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  raciones_producidas BIGINT NOT NULL CHECK(raciones_producidas>=0),
  raciones_servidas BIGINT NOT NULL CHECK(raciones_servidas>=0),
  raciones_excedentes BIGINT NOT NULL CHECK(raciones_excedentes>=0),
  usuario_id BIGINT NOT NULL,
  observacion TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,minuta_id) REFERENCES minuta(empresa_id,id),
  FOREIGN KEY(empresa_id,operacion_servicio_id) REFERENCES operacion_servicio(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id)
);

CREATE INDEX ix_produccion_empresa ON produccion(empresa_id);

CREATE TABLE produccion_documento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  produccion_id BIGINT NOT NULL,
  documento_stock_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,produccion_id) REFERENCES produccion(empresa_id,id),
  FOREIGN KEY(empresa_id,documento_stock_id) REFERENCES documento_stock(empresa_id,id),
  UNIQUE(empresa_id,documento_stock_id)
);

CREATE INDEX ix_produccion_documento_empresa ON produccion_documento(empresa_id);

CREATE TABLE merma_produccion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  produccion_id BIGINT NOT NULL,
  variante_id BIGINT,
  receta_version_id BIGINT,
  etapa TEXT NOT NULL,
  cantidad_u6 BIGINT NOT NULL CHECK(cantidad_u6>0),
  unidad_id BIGINT NOT NULL,
  motivo TEXT NOT NULL,
  ya_incluida_consumo BIGINT NOT NULL DEFAULT 1 CHECK(ya_incluida_consumo IN (0,1)),
  documento_baja_id BIGINT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,produccion_id) REFERENCES produccion(empresa_id,id),
  FOREIGN KEY(empresa_id,variante_id) REFERENCES variante_producto(empresa_id,id),
  FOREIGN KEY(empresa_id,receta_version_id) REFERENCES receta_version(empresa_id,id),
  FOREIGN KEY(empresa_id,unidad_id) REFERENCES unidad_medida(empresa_id,id),
  FOREIGN KEY(empresa_id,documento_baja_id) REFERENCES documento_stock(empresa_id,id),
  CHECK(variante_id IS NOT NULL OR receta_version_id IS NOT NULL)
);

CREATE INDEX ix_merma_produccion_empresa ON merma_produccion(empresa_id);

CREATE TABLE inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  almacen_id BIGINT NOT NULL,
  numero TEXT NOT NULL,
  fecha_corte DATE NOT NULL,
  tipo TEXT NOT NULL CHECK(tipo IN ('general','rotativo')),
  estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','contado','revisado','cerrado')),
  usuario_id BIGINT NOT NULL,
  revisor_id BIGINT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,almacen_id) REFERENCES almacen(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id),
  FOREIGN KEY(empresa_id,revisor_id) REFERENCES usuario(empresa_id,id),
  UNIQUE(empresa_id,numero)
);

CREATE INDEX ix_inventario_empresa ON inventario(empresa_id);

CREATE TABLE inventario_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  inventario_id BIGINT NOT NULL,
  variante_id BIGINT NOT NULL,
  stock_sistema_u6 BIGINT NOT NULL CHECK(stock_sistema_u6>=0),
  fisico_u6 BIGINT CHECK(fisico_u6>=0),
  costo_corte_u6 BIGINT NOT NULL CHECK(costo_corte_u6>=0),
  observacion TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,inventario_id) REFERENCES inventario(empresa_id,id),
  FOREIGN KEY(empresa_id,variante_id) REFERENCES variante_producto(empresa_id,id),
  UNIQUE(empresa_id,inventario_id,variante_id)
);

CREATE INDEX ix_inventario_detalle_empresa ON inventario_detalle(empresa_id);

CREATE TABLE inventario_ajuste (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  inventario_detalle_id BIGINT NOT NULL,
  documento_stock_id BIGINT NOT NULL,
  autorizador_id BIGINT NOT NULL,
  motivo TEXT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,inventario_detalle_id) REFERENCES inventario_detalle(empresa_id,id),
  FOREIGN KEY(empresa_id,documento_stock_id) REFERENCES documento_stock(empresa_id,id),
  FOREIGN KEY(empresa_id,autorizador_id) REFERENCES usuario(empresa_id,id),
  UNIQUE(empresa_id,inventario_detalle_id)
);

CREATE INDEX ix_inventario_ajuste_empresa ON inventario_ajuste(empresa_id);

CREATE TABLE periodo_mensual (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  operacion_id BIGINT NOT NULL,
  anio BIGINT NOT NULL CHECK(anio BETWEEN 2000 AND 2200),
  mes BIGINT NOT NULL CHECK(mes BETWEEN 1 AND 12),
  estado TEXT NOT NULL DEFAULT 'abierto' CHECK(estado IN ('abierto','en_revision','cerrado')),
  metodo_valoracion TEXT,
  usuario_cierre_id BIGINT,
  fecha_cierre TIMESTAMPTZ,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,operacion_id) REFERENCES operacion(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_cierre_id) REFERENCES usuario(empresa_id,id),
  UNIQUE(empresa_id,operacion_id,anio,mes)
);

CREATE INDEX ix_periodo_mensual_empresa ON periodo_mensual(empresa_id);

CREATE TABLE cierre_diario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  operacion_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  estado TEXT NOT NULL DEFAULT 'abierto' CHECK(estado IN ('abierto','cerrado')),
  usuario_cierre_id BIGINT,
  fecha_cierre TIMESTAMPTZ,
  estado_envio TEXT NOT NULL DEFAULT 'pendiente' CHECK(estado_envio IN ('pendiente','enviado','error')),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,operacion_id) REFERENCES operacion(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_cierre_id) REFERENCES usuario(empresa_id,id),
  UNIQUE(empresa_id,operacion_id,fecha)
);

CREATE INDEX ix_cierre_diario_empresa ON cierre_diario(empresa_id);

CREATE TABLE cierre_validacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  periodo_id BIGINT,
  cierre_diario_id BIGINT,
  codigo TEXT NOT NULL,
  resultado TEXT NOT NULL,
  detalle TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,periodo_id) REFERENCES periodo_mensual(empresa_id,id),
  FOREIGN KEY(empresa_id,cierre_diario_id) REFERENCES cierre_diario(empresa_id,id),
  CHECK((periodo_id IS NOT NULL)::int+(cierre_diario_id IS NOT NULL)::int=1)
);

CREATE INDEX ix_cierre_validacion_empresa ON cierre_validacion(empresa_id);

CREATE TABLE ingreso_servicio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  operacion_servicio_id BIGINT NOT NULL,
  periodo_id BIGINT NOT NULL,
  importe_neto_u6 BIGINT NOT NULL CHECK(importe_neto_u6>=0),
  ajustes_u6 BIGINT NOT NULL DEFAULT 0,
  moneda TEXT NOT NULL,
  fuente TEXT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,operacion_servicio_id) REFERENCES operacion_servicio(empresa_id,id),
  FOREIGN KEY(empresa_id,periodo_id) REFERENCES periodo_mensual(empresa_id,id),
  UNIQUE(empresa_id,operacion_servicio_id,periodo_id)
);

CREATE INDEX ix_ingreso_servicio_empresa ON ingreso_servicio(empresa_id);

CREATE TABLE gasto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  periodo_id BIGINT NOT NULL,
  operacion_servicio_id BIGINT,
  concepto TEXT NOT NULL,
  categoria TEXT NOT NULL,
  cuenta_contable TEXT,
  importe_u6 BIGINT NOT NULL CHECK(importe_u6>=0),
  moneda TEXT NOT NULL,
  es_proyectado BIGINT NOT NULL DEFAULT 0,
  usuario_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,periodo_id) REFERENCES periodo_mensual(empresa_id,id),
  FOREIGN KEY(empresa_id,operacion_servicio_id) REFERENCES operacion_servicio(empresa_id,id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id)
);

CREATE INDEX ix_gasto_empresa ON gasto(empresa_id);

CREATE TABLE cliente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  identificacion_fiscal TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_cliente_empresa ON cliente(empresa_id);

CREATE TABLE contrato (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  cliente_id BIGINT NOT NULL,
  operacion_id BIGINT NOT NULL,
  codigo TEXT NOT NULL,
  fecha_desde DATE NOT NULL,
  fecha_hasta DATE,
  moneda TEXT NOT NULL,
  condiciones TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,cliente_id) REFERENCES cliente(empresa_id,id),
  FOREIGN KEY(empresa_id,operacion_id) REFERENCES operacion(empresa_id,id),
  CHECK(fecha_hasta IS NULL OR fecha_hasta>=fecha_desde),
  UNIQUE(empresa_id,codigo)
);

CREATE INDEX ix_contrato_empresa ON contrato(empresa_id);

CREATE TABLE contrato_servicio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  contrato_id BIGINT NOT NULL,
  operacion_servicio_id BIGINT NOT NULL,
  importe_mensual_u6 BIGINT NOT NULL CHECK(importe_mensual_u6>=0),
  fecha_desde DATE NOT NULL,
  fecha_hasta DATE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,contrato_id) REFERENCES contrato(empresa_id,id),
  FOREIGN KEY(empresa_id,operacion_servicio_id) REFERENCES operacion_servicio(empresa_id,id),
  CHECK(fecha_hasta IS NULL OR fecha_hasta>=fecha_desde)
);

CREATE INDEX ix_contrato_servicio_empresa ON contrato_servicio(empresa_id);

CREATE TABLE auditoria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  usuario_id BIGINT,
  tabla TEXT NOT NULL,
  registro_id BIGINT NOT NULL,
  accion TEXT NOT NULL,
  antes_json TEXT,
  despues_json TEXT,
  fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,usuario_id) REFERENCES usuario(empresa_id,id)
);

CREATE INDEX ix_auditoria_empresa ON auditoria(empresa_id);

CREATE TABLE sincronizacion_evento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  uuid TEXT NOT NULL,
  operacion_id BIGINT NOT NULL,
  tipo TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  version_origen BIGINT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'pendiente' CHECK(estado IN ('pendiente','enviado','error','conflicto')),
  intentos BIGINT NOT NULL DEFAULT 0,
  ultimo_error TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  FOREIGN KEY(empresa_id,operacion_id) REFERENCES operacion(empresa_id,id),
  UNIQUE(empresa_id,uuid)
);

CREATE INDEX ix_sincronizacion_evento_empresa ON sincronizacion_evento(empresa_id);

CREATE TABLE integracion_envio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  sistema_destino TEXT NOT NULL,
  clave_idempotencia TEXT NOT NULL,
  tipo TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'pendiente',
  respuesta_json TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(empresa_id,id),
  FOREIGN KEY(empresa_id) REFERENCES empresa(id),
  UNIQUE(empresa_id,sistema_destino,clave_idempotencia)
);

CREATE INDEX ix_integracion_envio_empresa ON integracion_envio(empresa_id);

-- Vistas
CREATE VIEW v_kardex AS SELECT m.*,p.codigo AS codigo_producto,p.descripcion AS producto,v.codigo AS codigo_variante,v.descripcion_comercial,u.codigo AS unidad,
 SUM(m.signo*m.cantidad_base_u6) OVER(PARTITION BY m.empresa_id,m.almacen_id,m.variante_id ORDER BY m.secuencia) AS saldo_cantidad_u6,
 SUM(m.signo*m.valor_u6) OVER(PARTITION BY m.empresa_id,m.almacen_id,m.variante_id ORDER BY m.secuencia) AS saldo_valor_u6
 FROM movimiento_stock m JOIN variante_producto v ON v.empresa_id=m.empresa_id AND v.id=m.variante_id JOIN producto_base p ON p.empresa_id=v.empresa_id AND p.id=v.producto_base_id JOIN unidad_medida u ON u.empresa_id=p.empresa_id AND u.id=p.unidad_base_id;

CREATE VIEW v_stock_producto AS SELECT s.empresa_id,s.almacen_id,v.producto_base_id,SUM(s.cantidad_base_u6) AS cantidad_base_u6,SUM(s.valor_u6) AS valor_u6 FROM saldo_stock s JOIN variante_producto v ON v.empresa_id=s.empresa_id AND v.id=s.variante_id GROUP BY s.empresa_id,s.almacen_id,v.producto_base_id;

CREATE VIEW v_diferencias_inventario AS SELECT i.*,i.fisico_u6-i.stock_sistema_u6 AS diferencia_u6,CASE WHEN i.fisico_u6 IS NULL THEN 'sin contar' WHEN i.fisico_u6>i.stock_sistema_u6 THEN 'sobrante' WHEN i.fisico_u6<i.stock_sistema_u6 THEN 'faltante' ELSE 'sin diferencia' END AS resultado FROM inventario_detalle i;

CREATE VIEW v_empaque_conversion AS SELECT e.*,v.contenido_base_por_envase_u6,e.envases_por_empaque*v.contenido_base_por_envase_u6 AS contenido_base_total_u6 FROM empaque_compra e JOIN variante_producto v ON v.empresa_id=e.empresa_id AND v.id=e.variante_id;
