-- V015: planificación teórica vs ejecución real del servicio (pedido del usuario).
--
-- * Los factores de consumo de la estructura son teóricos; cada OPERACIÓN puede ajustarlos a su consumo real
--   (factor_consumo_operacion). La minuta guarda el factor y el reparto con que se calcularon sus raciones, para
--   recalcularlas si cambia el total de comensales mientras está en borrador.
-- * Después del servicio se registra lo REAL: raciones preparadas y consumidas por componente (consumo_plato) y la
--   VENTA real del servicio (venta_servicio: raciones vendidas e importe).
-- * Con eso se compara planificado vs realizado: raciones, venta, costo y productos (incluidos los que salieron del
--   almacén para el servicio sin estar en la planificación).
-- Lo real de un día cerrado no se modifica.

-- ---------- Factores por operación ----------
CREATE TABLE factor_consumo_operacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_servicio_id BIGINT NOT NULL,
  estructura_id BIGINT NOT NULL,
  factor_consumo_bp BIGINT NOT NULL CHECK (factor_consumo_bp BETWEEN 0 AND 10000),
  usuario_id BIGINT NOT NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (empresa_id, operacion_servicio_id) REFERENCES operacion_servicio(empresa_id, id),
  FOREIGN KEY (empresa_id, estructura_id) REFERENCES estructura_servicio(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id),
  UNIQUE (empresa_id, operacion_servicio_id, estructura_id)
);

CREATE FUNCTION fn_validar_factor_operacion() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM operacion_servicio os JOIN estructura_servicio es ON es.empresa_id = os.empresa_id AND es.servicio_id = os.servicio_id
                  WHERE os.empresa_id = NEW.empresa_id AND os.id = NEW.operacion_servicio_id AND es.id = NEW.estructura_id) THEN
    RAISE EXCEPTION 'ESTRUCTURA_DE_OTRO_SERVICIO: el componente no pertenece al servicio';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER validar_factor_operacion BEFORE INSERT OR UPDATE ON factor_consumo_operacion
  FOR EACH ROW EXECUTE FUNCTION fn_validar_factor_operacion();

-- ---------- Minuta: con qué factor y reparto se calcularon las raciones ----------
ALTER TABLE minuta_detalle
  ADD COLUMN factor_consumo_bp BIGINT CHECK (factor_consumo_bp BETWEEN 0 AND 10000),
  ADD COLUMN reparto_bp BIGINT CHECK (reparto_bp BETWEEN 0 AND 10000);

-- ---------- Real: consumo por componente y venta del servicio ----------
CREATE TABLE consumo_plato (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  minuta_detalle_id BIGINT NOT NULL,
  raciones_preparadas BIGINT NOT NULL CHECK (raciones_preparadas >= 0),
  raciones_consumidas BIGINT NOT NULL CHECK (raciones_consumidas >= 0),
  usuario_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (empresa_id, minuta_detalle_id) REFERENCES minuta_detalle(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id),
  UNIQUE (empresa_id, minuta_detalle_id),
  CHECK (raciones_consumidas <= raciones_preparadas)
);

CREATE TABLE venta_servicio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  minuta_id BIGINT NOT NULL,
  raciones_vendidas BIGINT NOT NULL CHECK (raciones_vendidas >= 0),
  importe_u6 BIGINT NOT NULL CHECK (importe_u6 >= 0),
  fuente TEXT NOT NULL,
  usuario_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (empresa_id, minuta_id) REFERENCES minuta(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id),
  UNIQUE (empresa_id, minuta_id)
);

-- Lo real se registra sobre una minuta aprobada y nunca en un día cerrado.
CREATE FUNCTION fn_proteger_dato_real() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_empresa bigint; v_minuta bigint; m record;
BEGIN
  v_empresa := COALESCE(NEW.empresa_id, OLD.empresa_id);
  IF TG_TABLE_NAME = 'consumo_plato' THEN
    SELECT minuta_id INTO v_minuta FROM minuta_detalle WHERE empresa_id = v_empresa AND id = COALESCE(NEW.minuta_detalle_id, OLD.minuta_detalle_id);
  ELSE
    v_minuta := COALESCE(NEW.minuta_id, OLD.minuta_id);
  END IF;
  SELECT mi.estado, mi.fecha, os.operacion_id INTO m FROM minuta mi JOIN operacion_servicio os ON os.empresa_id = mi.empresa_id AND os.id = mi.operacion_servicio_id
   WHERE mi.empresa_id = v_empresa AND mi.id = v_minuta;
  IF m.estado = 'borrador' THEN
    RAISE EXCEPTION 'MINUTA_NO_APROBADA: lo real se registra sobre una minuta aprobada';
  END IF;
  IF EXISTS (SELECT 1 FROM cierre_diario c WHERE c.empresa_id = v_empresa AND c.operacion_id = m.operacion_id AND c.fecha = m.fecha AND c.estado = 'cerrado') THEN
    RAISE EXCEPTION 'DIA_CERRADO: el dia % esta cerrado', m.fecha;
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$;
CREATE TRIGGER proteger_dato_real BEFORE INSERT OR UPDATE OR DELETE ON consumo_plato  FOR EACH ROW EXECUTE FUNCTION fn_proteger_dato_real();
CREATE TRIGGER proteger_dato_real BEFORE INSERT OR UPDATE OR DELETE ON venta_servicio FOR EACH ROW EXECUTE FUNCTION fn_proteger_dato_real();

-- ---------- Permisos, aislamiento y auditoría ----------
GRANT SELECT, INSERT, UPDATE, DELETE ON factor_consumo_operacion, consumo_plato, venta_servicio TO app_stock;
GRANT USAGE, SELECT ON SEQUENCE factor_consumo_operacion_id_seq, consumo_plato_id_seq, venta_servicio_id_seq TO app_stock;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['factor_consumo_operacion','consumo_plato','venta_servicio'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY aislamiento_empresa ON %I FOR ALL TO app_stock
                    USING (empresa_id = fn_empresa_actual()) WITH CHECK (empresa_id = fn_empresa_actual())', t);
    EXECUTE format('CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON %I
                    FOR EACH ROW EXECUTE FUNCTION fn_auditar()', t);
  END LOOP;
END $$;
