-- V018: decisiones del usuario D02 y D03 (2026-10-03).
--
-- D03: los precios de compra NO incluyen IGV. Todo precio se registra sin IGV; la base lo exige.
-- D02: un ingrediente puede tener varios productos con precios distintos. El costo usa el precio del producto ACTIVO
--      en la operación, es decir el que está liberado y se usa allí, no el más barato. producto_operacion guarda
--      ese producto (una presentación por ingrediente y operación). Si la operación no liberó ninguno, el costeo usa
--      la presentación con el último ingreso al almacén de la operación. Sin ninguno de los dos, el costo queda
--      pendiente: no se elige un precio al azar.

-- ---------- D03: precio sin IGV ----------
ALTER TABLE precio_compra ADD CONSTRAINT precio_sin_igv CHECK (incluye_impuesto = 0);

-- ---------- D02: producto activo por operación ----------
-- La presentación debe ser del mismo ingrediente: FK compuesta con la clave (empresa, id, producto).
ALTER TABLE variante_producto ADD CONSTRAINT variante_producto_empresa_id_producto_key UNIQUE (empresa_id, id, producto_base_id);

CREATE TABLE producto_operacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_id BIGINT NOT NULL,
  producto_base_id BIGINT NOT NULL,
  variante_id BIGINT NOT NULL,
  motivo TEXT,
  usuario_id BIGINT NOT NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id),
  FOREIGN KEY (empresa_id, producto_base_id) REFERENCES producto_base(empresa_id, id),
  FOREIGN KEY (empresa_id, variante_id, producto_base_id) REFERENCES variante_producto(empresa_id, id, producto_base_id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id),
  UNIQUE (empresa_id, operacion_id, producto_base_id)
);
CREATE INDEX ix_producto_operacion_producto ON producto_operacion(empresa_id, producto_base_id);
CREATE INDEX ix_producto_operacion_variante ON producto_operacion(empresa_id, variante_id, producto_base_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON producto_operacion TO app_stock;
GRANT USAGE, SELECT ON SEQUENCE producto_operacion_id_seq TO app_stock;
ALTER TABLE producto_operacion ENABLE ROW LEVEL SECURITY;
CREATE POLICY aislamiento_empresa ON producto_operacion FOR ALL TO app_stock
  USING (empresa_id = fn_empresa_actual()) WITH CHECK (empresa_id = fn_empresa_actual());
CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON producto_operacion FOR EACH ROW EXECUTE FUNCTION fn_auditar();
