-- V021: seguridad de cuatro niveles, fase 1 de Planificación y Abastecimiento Central (pedido del usuario, 2026-10-03).
--
-- * Módulo, pantalla y acción: cada código de permiso pertenece a una pantalla y una acción (catálogo en el dominio,
--   Seguridad.Pantallas). Aquí se agrega el cuarto nivel, el ALCANCE de cada asignación de rol:
--     OPERACION  la operación de la asignación (lo de siempre);
--     ZONA       todas las operaciones de la misma zona o región (operacion.zona) que la de la asignación;
--     TODAS      todas las operaciones de la empresa (p. ej. compras central).
-- * usuario_permiso: el superusuario (dueño) concede o niega un permiso a una persona fuera de su rol, en una
--   operación o en todas. Lo negado gana a lo que da el rol; al dueño no se le niega nada.
-- * fn_permisos_usuario y fn_tiene_permiso: los permisos efectivos se calculan en la base, una sola vez, y los usan
--   la aplicación al abrir la sesión y los triggers de las acciones críticas (mover stock y cambiar factores). Ocultar
--   un botón no basta: un usuario sin permiso tampoco puede hacerlo por SQL con la sesión de la aplicación.
-- * FACTORES_EDITAR: permiso propio para cambiar el factor de consumo de la operación (antes bastaba MINUTAS_APROBAR).
--   Se otorga a todos los roles que ya tenían MINUTAS_APROBAR, así nadie pierde lo que hacía.
-- Con la conexión del propietario o del instalador (sin app.usuario_id) las reglas de permiso no aplican.

-- ---------- Alcance de cada asignación de rol ----------
ALTER TABLE usuario_operacion_rol
  ADD COLUMN alcance TEXT NOT NULL DEFAULT 'OPERACION' CHECK (alcance IN ('OPERACION', 'ZONA', 'TODAS'));

CREATE FUNCTION fn_es_dueno_actual(p_empresa bigint) RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS (SELECT 1 FROM usuario d WHERE d.id = fn_usuario_actual() AND d.empresa_id = p_empresa AND d.es_dueno AND d.activo = 1)
$$;

CREATE FUNCTION fn_proteger_alcance() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.alcance <> 'OPERACION' AND (TG_OP = 'INSERT' OR NEW.alcance IS DISTINCT FROM OLD.alcance) THEN
    IF fn_usuario_actual() IS NOT NULL AND NOT fn_es_dueno_actual(NEW.empresa_id) THEN
      RAISE EXCEPTION 'SOLO_DUENO: solo el superusuario da acceso por zona o a todas las operaciones';
    END IF;
    IF NEW.alcance = 'ZONA' AND NOT EXISTS (SELECT 1 FROM operacion o WHERE o.id = NEW.operacion_id AND NULLIF(btrim(o.zona), '') IS NOT NULL) THEN
      RAISE EXCEPTION 'ZONA_NO_DEFINIDA: la operacion de la asignacion no tiene zona';
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER proteger_alcance BEFORE INSERT OR UPDATE ON usuario_operacion_rol FOR EACH ROW EXECUTE FUNCTION fn_proteger_alcance();

-- ---------- Permisos concedidos o negados a una persona (matriz de acceso) ----------
CREATE TABLE usuario_permiso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  usuario_id BIGINT NOT NULL,
  permiso_id BIGINT NOT NULL,
  operacion_id BIGINT,                                   -- NULL = en todas las operaciones
  concedido BOOLEAN NOT NULL,                            -- false = negado aunque el rol lo dé
  motivo TEXT,
  registrado_por BIGINT NOT NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id),
  FOREIGN KEY (empresa_id, permiso_id) REFERENCES permiso(empresa_id, id),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id),
  FOREIGN KEY (empresa_id, registrado_por) REFERENCES usuario(empresa_id, id),
  UNIQUE NULLS NOT DISTINCT (empresa_id, usuario_id, permiso_id, operacion_id)
);
CREATE INDEX ix_usuario_permiso_permiso ON usuario_permiso(empresa_id, permiso_id);
CREATE INDEX ix_usuario_permiso_operacion ON usuario_permiso(empresa_id, operacion_id) WHERE operacion_id IS NOT NULL;
CREATE INDEX ix_usuario_permiso_registrado_por ON usuario_permiso(empresa_id, registrado_por);

CREATE FUNCTION fn_proteger_usuario_permiso() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_empresa bigint := CASE WHEN TG_OP = 'DELETE' THEN OLD.empresa_id ELSE NEW.empresa_id END;
BEGIN
  IF fn_usuario_actual() IS NOT NULL AND NOT fn_es_dueno_actual(v_empresa) THEN
    RAISE EXCEPTION 'SOLO_DUENO: solo el superusuario modifica la matriz de acceso';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$;
CREATE TRIGGER proteger_usuario_permiso BEFORE INSERT OR UPDATE OR DELETE ON usuario_permiso
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_usuario_permiso();

GRANT SELECT, INSERT, UPDATE, DELETE ON usuario_permiso TO app_stock;
GRANT USAGE, SELECT ON SEQUENCE usuario_permiso_id_seq TO app_stock;
ALTER TABLE usuario_permiso ENABLE ROW LEVEL SECURITY;
CREATE POLICY aislamiento_empresa ON usuario_permiso FOR ALL TO app_stock
  USING (empresa_id = fn_empresa_actual()) WITH CHECK (empresa_id = fn_empresa_actual());
CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON usuario_permiso FOR EACH ROW EXECUTE FUNCTION fn_auditar();

-- ---------- Permisos efectivos ----------
-- Dueño activo: todos los permisos en toda operación activa. Los demás: lo que dan sus roles según el alcance, más lo
-- concedido, menos lo negado (en esa operación o en todas).
CREATE FUNCTION fn_permisos_usuario(p_usuario bigint, p_operacion bigint) RETURNS SETOF text LANGUAGE sql STABLE AS $$
  WITH us AS (SELECT id, empresa_id, es_dueno FROM usuario WHERE id = p_usuario AND activo = 1),
       op AS (SELECT o.id, o.empresa_id, NULLIF(btrim(o.zona), '') AS zona FROM operacion o JOIN us ON us.empresa_id = o.empresa_id
              WHERE o.id = p_operacion AND o.activo = 1),
       por_rol AS (
         SELECT p.codigo FROM usuario_operacion_rol uor
         JOIN op ON op.empresa_id = uor.empresa_id
         JOIN operacion base ON base.empresa_id = uor.empresa_id AND base.id = uor.operacion_id
         JOIN rol_permiso rp ON rp.empresa_id = uor.empresa_id AND rp.rol_id = uor.rol_id
         JOIN permiso p ON p.empresa_id = rp.empresa_id AND p.id = rp.permiso_id
         WHERE uor.usuario_id = p_usuario
           AND (uor.operacion_id = op.id OR uor.alcance = 'TODAS'
                OR (uor.alcance = 'ZONA' AND op.zona IS NOT NULL AND NULLIF(btrim(base.zona), '') = op.zona))),
       excepcion AS (
         SELECT p.codigo, up.concedido FROM usuario_permiso up
         JOIN op ON op.empresa_id = up.empresa_id
         JOIN permiso p ON p.empresa_id = up.empresa_id AND p.id = up.permiso_id
         WHERE up.usuario_id = p_usuario AND (up.operacion_id IS NULL OR up.operacion_id = op.id))
  SELECT p.codigo FROM permiso p JOIN us ON us.empresa_id = p.empresa_id WHERE us.es_dueno AND EXISTS (SELECT 1 FROM op)
  UNION
  (SELECT codigo FROM por_rol WHERE NOT EXISTS (SELECT 1 FROM us WHERE us.es_dueno)
   UNION SELECT codigo FROM excepcion WHERE concedido AND NOT EXISTS (SELECT 1 FROM us WHERE us.es_dueno)
   EXCEPT SELECT codigo FROM excepcion WHERE NOT concedido)
$$;

-- Operaciones activas a las que la persona entra (alguna operación con al menos un permiso).
CREATE FUNCTION fn_operaciones_usuario(p_usuario bigint) RETURNS SETOF bigint LANGUAGE sql STABLE AS $$
  SELECT o.id FROM operacion o WHERE o.activo = 1 AND EXISTS (SELECT 1 FROM fn_permisos_usuario(p_usuario, o.id))
$$;

-- Para los triggers: ¿el usuario de la sesión tiene el permiso en la operación (NULL = en alguna)?
CREATE FUNCTION fn_tiene_permiso(p_codigo text, p_operacion bigint) RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT CASE
    WHEN fn_usuario_actual() IS NULL THEN true
    WHEN p_operacion IS NULL THEN EXISTS (SELECT 1 FROM fn_operaciones_usuario(fn_usuario_actual()) x(id)
                                          WHERE p_codigo IN (SELECT fn_permisos_usuario(fn_usuario_actual(), x.id)))
    ELSE p_codigo IN (SELECT fn_permisos_usuario(fn_usuario_actual(), p_operacion))
  END
$$;

GRANT EXECUTE ON FUNCTION fn_permisos_usuario(bigint, bigint), fn_operaciones_usuario(bigint), fn_tiene_permiso(text, bigint),
  fn_es_dueno_actual(bigint) TO app_stock;

-- ---------- Acciones críticas validadas en la base ----------
-- Mover stock: STOCK_CONTABILIZAR en la operación del almacén (T54: el planificador no mueve stock).
CREATE FUNCTION fn_exigir_permiso_stock() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT fn_tiene_permiso('STOCK_CONTABILIZAR', (SELECT a.operacion_id FROM almacen a WHERE a.id = NEW.almacen_id)) THEN
    RAISE EXCEPTION 'SIN_PERMISO: el usuario no puede mover stock en esa operacion';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER exigir_permiso_stock BEFORE INSERT ON movimiento_stock FOR EACH ROW EXECUTE FUNCTION fn_exigir_permiso_stock();

-- Factor de consumo de la operación: FACTORES_EDITAR en esa operación (T53: almacén no cambia factores).
CREATE FUNCTION fn_exigir_permiso_factor_operacion() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_os bigint := CASE WHEN TG_OP = 'DELETE' THEN OLD.operacion_servicio_id ELSE NEW.operacion_servicio_id END;
BEGIN
  IF NOT fn_tiene_permiso('FACTORES_EDITAR', (SELECT os.operacion_id FROM operacion_servicio os WHERE os.id = v_os)) THEN
    RAISE EXCEPTION 'SIN_PERMISO: el usuario no puede cambiar factores en esa operacion';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$;
CREATE TRIGGER exigir_permiso_factor BEFORE INSERT OR UPDATE OR DELETE ON factor_consumo_operacion
  FOR EACH ROW EXECUTE FUNCTION fn_exigir_permiso_factor_operacion();

-- Factor teórico del componente (central): MENUS_CONFIGURAR en alguna operación.
CREATE FUNCTION fn_exigir_permiso_factor_teorico() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (TG_OP = 'INSERT' OR NEW.factor_consumo_bp IS DISTINCT FROM OLD.factor_consumo_bp)
     AND NOT fn_tiene_permiso('MENUS_CONFIGURAR', NULL) THEN
    RAISE EXCEPTION 'SIN_PERMISO: el usuario no puede cambiar los factores teoricos';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER exigir_permiso_factor BEFORE INSERT OR UPDATE ON estructura_servicio
  FOR EACH ROW EXECUTE FUNCTION fn_exigir_permiso_factor_teorico();

-- ---------- FACTORES_EDITAR en las empresas ya instaladas ----------
INSERT INTO permiso(empresa_id, codigo, descripcion)
SELECT e.id, 'FACTORES_EDITAR', 'Cambiar el factor de consumo de la operacion'
FROM empresa e WHERE NOT EXISTS (SELECT 1 FROM permiso p WHERE p.empresa_id = e.id AND p.codigo = 'FACTORES_EDITAR');

INSERT INTO rol_permiso(empresa_id, rol_id, permiso_id)
SELECT rp.empresa_id, rp.rol_id, nuevo.id
FROM rol_permiso rp
JOIN permiso ma ON ma.empresa_id = rp.empresa_id AND ma.id = rp.permiso_id AND ma.codigo = 'MINUTAS_APROBAR'
JOIN permiso nuevo ON nuevo.empresa_id = rp.empresa_id AND nuevo.codigo = 'FACTORES_EDITAR'
ON CONFLICT (empresa_id, rol_id, permiso_id) DO NOTHING;
