-- V022: planificación central con versiones, fase 2 de Planificación y Abastecimiento Central (2026-10-04).
--
-- * planificacion: una por operación destino y periodo (código PLAN-AAAA-MM-XXX). No guarda cifras: las tiene cada versión.
-- * planificacion_version: BORRADOR -> APROBADO -> REEMPLAZADO. Una sola BORRADOR y una sola APROBADO por planificación
--   (índices parciales). Aprobar exige MINUTAS_APROBAR y al menos un servicio.
-- * Inmutabilidad (T49): una versión APROBADO o REEMPLAZADO no cambia en ninguna columna, y sus servicios, platos y
--   productos no se crean, cambian ni borran. Para cambiar algo se crea una versión nueva.
-- * Nueva versión (T56): crear la versión n+1 no toca las filas de la versión aprobada. Solo su estado pasa a
--   REEMPLAZADO, en la misma transacción en que se aprueba la nueva. La protección de un plan ya ejecutado (un
--   minuta que lo usa) llega con V023, cuando exista la liberación.
-- * planificacion_estado: historial que escribe la base al cambiar el estado de una versión (no lo escribe la aplicación).
--   Es de solo lectura.
-- * Permisos en la base: preparar (crear, editar contenido) exige MINUTAS_EDITAR y aprobar o reemplazar exige
--   MINUTAS_APROBAR, ambos por la operación destino (fn_tiene_permiso). Con la conexión del propietario o del instalador
--   no se aplican, como en V021.
-- Todas las tablas: empresa_id, FK compuestas, índice en cada clave foránea, RLS aislamiento_empresa, GRANT a app_stock y auditar.

-- ---------- Funciones auxiliares ----------
CREATE FUNCTION fn_operacion_planificacion(p_empresa bigint, p_planificacion bigint) RETURNS bigint
  LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN (SELECT p.operacion_id FROM planificacion p WHERE p.empresa_id = p_empresa AND p.id = p_planificacion);
END $$;

-- ---------- Planificación (cabecera) ----------
CREATE TABLE planificacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  codigo TEXT NOT NULL CHECK (btrim(codigo) <> ''),
  operacion_id BIGINT NOT NULL,
  periodo_desde DATE NOT NULL,
  periodo_hasta DATE NOT NULL,
  regimen_id BIGINT NOT NULL,
  creado_por BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, codigo),
  UNIQUE (empresa_id, operacion_id, periodo_desde),
  CHECK (periodo_hasta >= periodo_desde),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id),
  FOREIGN KEY (empresa_id, regimen_id) REFERENCES regimen(empresa_id, id),
  FOREIGN KEY (empresa_id, creado_por) REFERENCES usuario(empresa_id, id)
);
CREATE INDEX ix_planificacion_regimen ON planificacion(empresa_id, regimen_id);
CREATE INDEX ix_planificacion_creado_por ON planificacion(empresa_id, creado_por);

CREATE FUNCTION fn_proteger_planificacion() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF fn_usuario_actual() IS NOT NULL AND NOT fn_tiene_permiso('MINUTAS_EDITAR', OLD.operacion_id) THEN
      RAISE EXCEPTION 'SIN_PERMISO: no puede quitar esta planificacion';
    END IF;
    RETURN OLD;
  END IF;
  IF fn_usuario_actual() IS NOT NULL AND NOT fn_tiene_permiso('MINUTAS_EDITAR', NEW.operacion_id) THEN
    RAISE EXCEPTION 'SIN_PERMISO: no puede preparar planificaciones de esta operacion';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER proteger_planificacion BEFORE INSERT OR UPDATE OR DELETE ON planificacion
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_planificacion();

-- ---------- Versiones ----------
CREATE TABLE planificacion_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  planificacion_id BIGINT NOT NULL,
  numero BIGINT NOT NULL CHECK (numero > 0),
  estado TEXT NOT NULL DEFAULT 'BORRADOR' CHECK (estado IN ('BORRADOR', 'APROBADO', 'REEMPLAZADO')),
  food_cost_objetivo_bp BIGINT CHECK (food_cost_objetivo_bp BETWEEN 0 AND 10000),
  costo_total_u6 BIGINT NOT NULL DEFAULT 0 CHECK (costo_total_u6 >= 0),
  venta_total_u6 BIGINT NOT NULL DEFAULT 0 CHECK (venta_total_u6 >= 0),
  version_anterior_id BIGINT,
  motivo_cambio TEXT,
  creado_por BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  aprobado_por BIGINT,
  aprobado_en TIMESTAMPTZ,
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, planificacion_id, numero),
  CHECK ((numero = 1) = (version_anterior_id IS NULL)),
  CHECK ((numero = 1) OR btrim(motivo_cambio) <> ''),
  CHECK (estado = 'BORRADOR' OR (aprobado_por IS NOT NULL AND aprobado_en IS NOT NULL)),
  FOREIGN KEY (empresa_id, planificacion_id) REFERENCES planificacion(empresa_id, id),
  FOREIGN KEY (empresa_id, version_anterior_id) REFERENCES planificacion_version(empresa_id, id),
  FOREIGN KEY (empresa_id, creado_por) REFERENCES usuario(empresa_id, id),
  FOREIGN KEY (empresa_id, aprobado_por) REFERENCES usuario(empresa_id, id)
);
-- Una sola versión en borrador y una sola aprobada por planificación.
CREATE UNIQUE INDEX ux_planificacion_version_borrador ON planificacion_version(empresa_id, planificacion_id) WHERE estado = 'BORRADOR';
CREATE UNIQUE INDEX ux_planificacion_version_aprobada ON planificacion_version(empresa_id, planificacion_id) WHERE estado = 'APROBADO';
CREATE INDEX ix_planificacion_version_anterior ON planificacion_version(empresa_id, version_anterior_id);
CREATE INDEX ix_planificacion_version_creado_por ON planificacion_version(empresa_id, creado_por);
CREATE INDEX ix_planificacion_version_aprobado_por ON planificacion_version(empresa_id, aprobado_por);

CREATE FUNCTION fn_proteger_planificacion_version() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_op bigint;
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.estado <> 'BORRADOR' THEN
      RAISE EXCEPTION 'VERSION_INMUTABLE: una version aprobada o reemplazada no se borra';
    END IF;
    IF fn_usuario_actual() IS NOT NULL AND NOT fn_tiene_permiso('MINUTAS_EDITAR', fn_operacion_planificacion(OLD.empresa_id, OLD.planificacion_id)) THEN
      RAISE EXCEPTION 'SIN_PERMISO: no puede quitar esta version';
    END IF;
    RETURN OLD;
  END IF;

  v_op := fn_operacion_planificacion(NEW.empresa_id, NEW.planificacion_id);

  IF TG_OP = 'INSERT' THEN
    IF NEW.estado <> 'BORRADOR' THEN
      RAISE EXCEPTION 'VERSION_INMUTABLE: una version nueva empieza en BORRADOR';
    END IF;
    IF fn_usuario_actual() IS NOT NULL AND NOT fn_tiene_permiso('MINUTAS_EDITAR', v_op) THEN
      RAISE EXCEPTION 'SIN_PERMISO: no puede preparar versiones de esta operacion';
    END IF;
    RETURN NEW;
  END IF;

  IF OLD.estado = 'BORRADOR' AND NEW.estado = 'BORRADOR' THEN
    IF NEW.planificacion_id <> OLD.planificacion_id OR NEW.numero <> OLD.numero THEN
      RAISE EXCEPTION 'VERSION_INMUTABLE: no se cambia la planificacion ni el numero de la version';
    END IF;
    IF fn_usuario_actual() IS NOT NULL AND NOT fn_tiene_permiso('MINUTAS_EDITAR', v_op) THEN
      RAISE EXCEPTION 'SIN_PERMISO: no puede editar versiones de esta operacion';
    END IF;
  ELSIF OLD.estado = 'BORRADOR' AND NEW.estado = 'APROBADO' THEN
    IF fn_usuario_actual() IS NOT NULL AND NOT fn_tiene_permiso('MINUTAS_APROBAR', v_op) THEN
      RAISE EXCEPTION 'SIN_PERMISO: no puede aprobar versiones de esta operacion';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM planificacion_servicio s WHERE s.empresa_id = NEW.empresa_id AND s.version_id = NEW.id) THEN
      RAISE EXCEPTION 'VERSION_VACIA: la version no tiene servicios';
    END IF;
  ELSIF OLD.estado = 'APROBADO' AND NEW.estado = 'REEMPLAZADO' THEN
    -- Solo se retira la versión aprobada para dar paso a una más nueva; sus filas quedan como estaban.
    IF fn_usuario_actual() IS NOT NULL AND NOT fn_tiene_permiso('MINUTAS_APROBAR', v_op) THEN
      RAISE EXCEPTION 'SIN_PERMISO: no puede reemplazar versiones de esta operacion';
    END IF;
    IF ROW(NEW.planificacion_id, NEW.numero, NEW.food_cost_objetivo_bp, NEW.costo_total_u6, NEW.venta_total_u6,
           NEW.version_anterior_id, NEW.motivo_cambio, NEW.creado_por, NEW.creado_en, NEW.aprobado_por, NEW.aprobado_en)
       IS DISTINCT FROM
       ROW(OLD.planificacion_id, OLD.numero, OLD.food_cost_objetivo_bp, OLD.costo_total_u6, OLD.venta_total_u6,
           OLD.version_anterior_id, OLD.motivo_cambio, OLD.creado_por, OLD.creado_en, OLD.aprobado_por, OLD.aprobado_en) THEN
      RAISE EXCEPTION 'VERSION_INMUTABLE: al reemplazar una version solo cambia su estado';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM planificacion_version n WHERE n.empresa_id = NEW.empresa_id
                   AND n.planificacion_id = NEW.planificacion_id AND n.numero > NEW.numero) THEN
      RAISE EXCEPTION 'SIN_VERSION_NUEVA: para reemplazar una version hay que tener otra mas nueva';
    END IF;
  ELSE
    RAISE EXCEPTION 'VERSION_INMUTABLE: transicion de % a % no permitida', OLD.estado, NEW.estado;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER proteger_planificacion_version BEFORE INSERT OR UPDATE OR DELETE ON planificacion_version
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_planificacion_version();

-- ---------- Historial de estados (lo escribe la base; no se edita) ----------
CREATE TABLE planificacion_estado (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  version_id BIGINT NOT NULL,
  estado_anterior TEXT CHECK (estado_anterior IN ('BORRADOR', 'APROBADO', 'REEMPLAZADO')),
  estado_nuevo TEXT NOT NULL CHECK (estado_nuevo IN ('BORRADOR', 'APROBADO', 'REEMPLAZADO')),
  usuario_id BIGINT,
  ocurrido_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  observacion TEXT,
  UNIQUE (empresa_id, id),
  CHECK ((estado_anterior IS NULL) = (estado_nuevo = 'BORRADOR')),
  FOREIGN KEY (empresa_id, version_id) REFERENCES planificacion_version(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id)
);
CREATE INDEX ix_planificacion_estado_version ON planificacion_estado(empresa_id, version_id);
CREATE INDEX ix_planificacion_estado_usuario ON planificacion_estado(empresa_id, usuario_id);

CREATE FUNCTION fn_registrar_estado_version() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' OR NEW.estado IS DISTINCT FROM OLD.estado THEN
    INSERT INTO planificacion_estado(empresa_id, version_id, estado_anterior, estado_nuevo, usuario_id, ocurrido_en)
    VALUES (NEW.empresa_id, NEW.id, CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.estado END, NEW.estado, fn_usuario_actual(), now());
  END IF;
  RETURN NULL;
END $$;
CREATE TRIGGER registrar_estado_version AFTER INSERT OR UPDATE OF estado ON planificacion_version
  FOR EACH ROW EXECUTE FUNCTION fn_registrar_estado_version();

CREATE FUNCTION fn_historial_inmutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'HISTORIAL_INMUTABLE: el historial de estados no se cambia ni se borra';
END $$;
CREATE TRIGGER historial_inmutable BEFORE UPDATE OR DELETE ON planificacion_estado
  FOR EACH ROW EXECUTE FUNCTION fn_historial_inmutable();

-- ---------- Contenido de la versión: servicios, platos y productos ----------
CREATE TABLE planificacion_servicio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  version_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  servicio_id BIGINT NOT NULL,
  estructura_id BIGINT NOT NULL,
  comensales_previstos BIGINT NOT NULL CHECK (comensales_previstos >= 0),
  UNIQUE (empresa_id, version_id, id),
  UNIQUE (empresa_id, version_id, fecha, servicio_id, estructura_id),
  FOREIGN KEY (empresa_id, version_id) REFERENCES planificacion_version(empresa_id, id),
  FOREIGN KEY (empresa_id, servicio_id) REFERENCES servicio(empresa_id, id),
  FOREIGN KEY (empresa_id, estructura_id) REFERENCES estructura_servicio(empresa_id, id)
);
CREATE INDEX ix_planificacion_servicio_servicio ON planificacion_servicio(empresa_id, servicio_id);
CREATE INDEX ix_planificacion_servicio_estructura ON planificacion_servicio(empresa_id, estructura_id);

CREATE TABLE planificacion_plato (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  version_id BIGINT NOT NULL,
  servicio_planificado_id BIGINT NOT NULL,
  receta_id BIGINT NOT NULL,
  receta_version_id BIGINT NOT NULL,
  factor_teorico_bp BIGINT NOT NULL CHECK (factor_teorico_bp > 0),
  reparto_bp BIGINT NOT NULL CHECK (reparto_bp BETWEEN 0 AND 10000),
  raciones_u6 BIGINT NOT NULL CHECK (raciones_u6 >= 0),
  costo_racion_u6 BIGINT CHECK (costo_racion_u6 >= 0),
  fecha_precio DATE,
  UNIQUE (empresa_id, version_id, id),
  UNIQUE (empresa_id, version_id, servicio_planificado_id, receta_id),
  CHECK ((costo_racion_u6 IS NULL) = (fecha_precio IS NULL)),
  FOREIGN KEY (empresa_id, version_id) REFERENCES planificacion_version(empresa_id, id),
  FOREIGN KEY (empresa_id, version_id, servicio_planificado_id) REFERENCES planificacion_servicio(empresa_id, version_id, id),
  FOREIGN KEY (empresa_id, receta_id) REFERENCES receta(empresa_id, id),
  FOREIGN KEY (empresa_id, receta_version_id) REFERENCES receta_version(empresa_id, id)
);
CREATE INDEX ix_planificacion_plato_receta ON planificacion_plato(empresa_id, receta_id);
CREATE INDEX ix_planificacion_plato_receta_version ON planificacion_plato(empresa_id, receta_version_id);

CREATE TABLE planificacion_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  version_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  producto_base_id BIGINT NOT NULL,
  cantidad_requerida_u6 BIGINT NOT NULL CHECK (cantidad_requerida_u6 >= 0),
  precio_usado_u6 BIGINT CHECK (precio_usado_u6 >= 0),
  fecha_precio DATE,
  fuente_precio TEXT CHECK (fuente_precio IN ('PRECIO_COMPRA', 'ACUERDO')),
  UNIQUE (empresa_id, version_id, fecha, producto_base_id),
  -- Sin precio no hay precio: nunca 0 ni estimado.
  CHECK ((precio_usado_u6 IS NULL) = (fecha_precio IS NULL) AND (precio_usado_u6 IS NULL) = (fuente_precio IS NULL)),
  FOREIGN KEY (empresa_id, version_id) REFERENCES planificacion_version(empresa_id, id),
  FOREIGN KEY (empresa_id, producto_base_id) REFERENCES producto_base(empresa_id, id)
);
CREATE INDEX ix_planificacion_producto_base ON planificacion_producto(empresa_id, producto_base_id);

CREATE FUNCTION fn_proteger_contenido_version() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_empresa bigint := CASE WHEN TG_OP = 'DELETE' THEN OLD.empresa_id ELSE NEW.empresa_id END;
  v_version bigint := CASE WHEN TG_OP = 'DELETE' THEN OLD.version_id ELSE NEW.version_id END;
  v_estado text;
  v_op bigint;
BEGIN
  SELECT pv.estado, fn_operacion_planificacion(pv.empresa_id, pv.planificacion_id)
    INTO v_estado, v_op
    FROM planificacion_version pv
   WHERE pv.empresa_id = v_empresa AND pv.id = v_version;
  IF v_estado IS DISTINCT FROM 'BORRADOR' THEN
    RAISE EXCEPTION 'VERSION_INMUTABLE: la version no esta en borrador; para cambiar algo se crea una version nueva';
  END IF;
  IF TG_OP = 'UPDATE' AND OLD.version_id <> NEW.version_id THEN
    RAISE EXCEPTION 'VERSION_INMUTABLE: una fila no pasa a otra version';
  END IF;
  IF fn_usuario_actual() IS NOT NULL AND NOT fn_tiene_permiso('MINUTAS_EDITAR', v_op) THEN
    RAISE EXCEPTION 'SIN_PERMISO: no puede editar versiones de esta operacion';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$;
CREATE TRIGGER proteger_planificacion_servicio BEFORE INSERT OR UPDATE OR DELETE ON planificacion_servicio
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_contenido_version();
CREATE TRIGGER proteger_planificacion_plato BEFORE INSERT OR UPDATE OR DELETE ON planificacion_plato
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_contenido_version();
CREATE TRIGGER proteger_planificacion_producto BEFORE INSERT OR UPDATE OR DELETE ON planificacion_producto
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_contenido_version();

-- ---------- Permisos, RLS y auditoría de las tablas nuevas ----------
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['planificacion', 'planificacion_version', 'planificacion_estado',
                           'planificacion_servicio', 'planificacion_plato', 'planificacion_producto'] LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO app_stock', t);
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %I_id_seq TO app_stock', t);
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY aislamiento_empresa ON %I FOR ALL TO app_stock
                      USING (empresa_id = fn_empresa_actual()) WITH CHECK (empresa_id = fn_empresa_actual())', t);
    EXECUTE format('CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON %I
                      FOR EACH ROW EXECUTE FUNCTION fn_auditar()', t);
  END LOOP;
END $$;
