-- V023: datos del plan teórico y real del SGP (Excel de datos/plan_real) guardados en el servidor, tal como llegaron.
--
-- Son la referencia importada de la operación: el plan teórico y el plan real por día y por plato, la requisición
-- detallada, los comparativos de tres niveles, el costo piso y techo y las preparaciones. El modelo operativo
-- (minutas con factores) no cambia: el plan real del SGP tiene raciones distintas cada día, y eso se lleva a la
-- planificación operativa en la fase 3.
--
-- * Los códigos del SGP se enlazan a las recetas y productos de AppSistema (sgp_codigo_receta, sgp_codigo_producto).
--   Un código sin enlace queda con la columna vacía: la receta o el producto no está entre los recibidos.
-- * Cantidades, raciones y dinero van en _u6; porcentajes en _bp. Comensales son personas (enteros).
-- * Reimportar reemplaza los datos de la operación (importar_plan_sgp), en una sola transacción.
-- * Todas las tablas: empresa_id, claves y FK compuestas, índice en cada clave foránea, RLS aislamiento_empresa,
--   GRANT a app_stock y auditar.

-- ---------- Códigos del SGP (catálogo de enlace) ----------
-- Estas tablas llevan id (la auditoría registra por id) y la clave natural única (la usan las FK).
CREATE TABLE sgp_codigo_receta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  codigo_sgp TEXT NOT NULL CHECK (btrim(codigo_sgp) <> ''),
  nombre_sgp TEXT NOT NULL,
  receta_id BIGINT,
  UNIQUE (empresa_id, codigo_sgp),
  FOREIGN KEY (empresa_id, receta_id) REFERENCES receta(empresa_id, id)
);
CREATE INDEX ix_sgp_codigo_receta_receta ON sgp_codigo_receta(empresa_id, receta_id);

CREATE TABLE sgp_codigo_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  codigo_sgp TEXT NOT NULL CHECK (btrim(codigo_sgp) <> ''),
  descripcion_sgp TEXT NOT NULL,
  unidad_bulto TEXT,
  unidad_despacho TEXT,
  -- El código PRD del SGP es la VARIANTE del catálogo (el producto que se compra y se despacha); el ING es el producto base.
  variante_id BIGINT,
  UNIQUE (empresa_id, codigo_sgp),
  FOREIGN KEY (empresa_id, variante_id) REFERENCES variante_producto(empresa_id, id)
);
CREATE INDEX ix_sgp_codigo_producto_variante ON sgp_codigo_producto(empresa_id, variante_id);

-- ---------- Plan por día (menú teórico y real) ----------
CREATE TABLE sgp_plan_dia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_id BIGINT NOT NULL,
  nivel TEXT NOT NULL CHECK (nivel IN ('TEORICO', 'REAL')),
  servicio TEXT NOT NULL,
  fecha DATE NOT NULL,
  comensales BIGINT NOT NULL CHECK (comensales >= 0),
  comensales_2 BIGINT CHECK (comensales_2 >= 0),
  costo_minuta_dia_u6 BIGINT NOT NULL CHECK (costo_minuta_dia_u6 >= 0),
  UNIQUE (empresa_id, operacion_id, nivel, servicio, fecha),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id)
);

-- ---------- Plan por plato ----------
CREATE TABLE sgp_plan_plato (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_id BIGINT NOT NULL,
  nivel TEXT NOT NULL CHECK (nivel IN ('TEORICO', 'REAL')),
  servicio TEXT NOT NULL,
  fecha DATE NOT NULL,
  orden BIGINT NOT NULL CHECK (orden > 0),
  estructura TEXT NOT NULL,
  receta_codigo_sgp TEXT NOT NULL,
  raciones_u6 BIGINT NOT NULL CHECK (raciones_u6 >= 0),
  -- Por.(%) = raciones / comensales: puede pasar de 100 % (un componente se sirve dos veces por comensal).
  porcentaje_bp BIGINT CHECK (porcentaje_bp >= 0),
  costo_racion_u6 BIGINT NOT NULL CHECK (costo_racion_u6 >= 0),
  marca TEXT,
  UNIQUE (empresa_id, operacion_id, nivel, servicio, fecha, orden),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id),
  FOREIGN KEY (empresa_id, receta_codigo_sgp) REFERENCES sgp_codigo_receta(empresa_id, codigo_sgp)
);
CREATE INDEX ix_sgp_plan_plato_receta ON sgp_plan_plato(empresa_id, receta_codigo_sgp);

-- ---------- Requisición detallada ----------
CREATE TABLE sgp_requisicion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_id BIGINT NOT NULL,
  regimen TEXT NOT NULL,
  servicio TEXT NOT NULL,
  fecha DATE NOT NULL,
  estructura TEXT NOT NULL,
  receta_codigo_sgp TEXT NOT NULL,
  raciones_u6 BIGINT NOT NULL CHECK (raciones_u6 >= 0),
  producto_codigo_sgp TEXT NOT NULL,
  cantidad_bruta_racion_u6 BIGINT NOT NULL CHECK (cantidad_bruta_racion_u6 >= 0),
  cantidad_bulto_u6 BIGINT NOT NULL CHECK (cantidad_bulto_u6 >= 0),
  unidad_bulto TEXT,
  cantidad_despacho_u6 BIGINT NOT NULL CHECK (cantidad_despacho_u6 >= 0),
  unidad_despacho TEXT,
  UNIQUE (empresa_id, operacion_id, regimen, servicio, fecha, estructura, receta_codigo_sgp, producto_codigo_sgp),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id),
  FOREIGN KEY (empresa_id, receta_codigo_sgp) REFERENCES sgp_codigo_receta(empresa_id, codigo_sgp),
  FOREIGN KEY (empresa_id, producto_codigo_sgp) REFERENCES sgp_codigo_producto(empresa_id, codigo_sgp)
);
CREATE INDEX ix_sgp_requisicion_receta ON sgp_requisicion(empresa_id, receta_codigo_sgp);
CREATE INDEX ix_sgp_requisicion_producto ON sgp_requisicion(empresa_id, producto_codigo_sgp);

-- ---------- Comparativos de tres niveles (por día y por total) ----------
CREATE TABLE sgp_comparativo_dia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_id BIGINT NOT NULL,
  contrato TEXT,
  regimen TEXT NOT NULL,
  servicio TEXT NOT NULL,
  fecha DATE NOT NULL,
  teorico_costo_bandeja_u6 BIGINT NOT NULL,
  teorico_raciones_u6 BIGINT NOT NULL,
  teorico_costo_total_u6 BIGINT NOT NULL,
  real_costo_bandeja_u6 BIGINT NOT NULL,
  real_raciones_u6 BIGINT NOT NULL,
  real_costo_total_u6 BIGINT NOT NULL,
  desviacion_plan_u6 BIGINT NOT NULL,
  realizado_costo_bandeja_u6 BIGINT NOT NULL,
  realizado_raciones_u6 BIGINT NOT NULL,
  realizado_costo_total_u6 BIGINT NOT NULL,
  desviacion_realizado_u6 BIGINT NOT NULL,
  UNIQUE (empresa_id, operacion_id, regimen, servicio, fecha),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id)
);

CREATE TABLE sgp_comparativo_total (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_id BIGINT NOT NULL,
  total TEXT NOT NULL,
  regimen TEXT NOT NULL,
  servicio TEXT NOT NULL,
  teorico_costo_bandeja_u6 BIGINT NOT NULL,
  teorico_raciones_u6 BIGINT NOT NULL,
  teorico_costo_total_u6 BIGINT NOT NULL,
  real_costo_bandeja_u6 BIGINT NOT NULL,
  real_raciones_u6 BIGINT NOT NULL,
  real_costo_total_u6 BIGINT NOT NULL,
  desviacion_plan_u6 BIGINT NOT NULL,
  realizado_costo_bandeja_u6 BIGINT NOT NULL,
  realizado_raciones_u6 BIGINT NOT NULL,
  realizado_costo_total_u6 BIGINT NOT NULL,
  desviacion_realizado_u6 BIGINT NOT NULL,
  UNIQUE (empresa_id, operacion_id, total, regimen, servicio),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id)
);

-- ---------- Costo piso y techo por factores (por nivel, servicio y mes) ----------
CREATE TABLE sgp_costo_piso_techo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_id BIGINT NOT NULL,
  nivel TEXT NOT NULL CHECK (nivel IN ('TEORICO', 'REAL')),
  servicio TEXT NOT NULL,
  mes TEXT NOT NULL CHECK (mes ~ '^[0-9]{4}-[0-9]{2}$'),
  componentes BIGINT NOT NULL CHECK (componentes >= 0),
  costo_piso_u6 BIGINT NOT NULL,
  costo_medio_u6 BIGINT NOT NULL,
  costo_techo_u6 BIGINT NOT NULL,
  dia_mas_barato_u6 BIGINT NOT NULL,
  dia_mas_caro_u6 BIGINT NOT NULL,
  dias_dentro TEXT NOT NULL,
  UNIQUE (empresa_id, operacion_id, nivel, servicio, mes),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id)
);

-- ---------- Preparación de las recetas, paso a paso ----------
CREATE TABLE sgp_preparacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  receta_codigo_sgp TEXT NOT NULL,
  orden BIGINT NOT NULL CHECK (orden > 0),
  paso TEXT NOT NULL,
  UNIQUE (empresa_id, receta_codigo_sgp, orden),
  FOREIGN KEY (empresa_id, receta_codigo_sgp) REFERENCES sgp_codigo_receta(empresa_id, codigo_sgp)
);

-- ---------- Permisos, RLS y auditoría ----------
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['sgp_codigo_receta', 'sgp_codigo_producto', 'sgp_plan_dia', 'sgp_plan_plato',
                           'sgp_requisicion', 'sgp_comparativo_dia', 'sgp_comparativo_total',
                           'sgp_costo_piso_techo', 'sgp_preparacion'] LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO app_stock', t);
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY aislamiento_empresa ON %I FOR ALL TO app_stock
                      USING (empresa_id = fn_empresa_actual()) WITH CHECK (empresa_id = fn_empresa_actual())', t);
    EXECUTE format('CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON %I
                      FOR EACH ROW EXECUTE FUNCTION fn_auditar()', t);
  END LOOP;
END $$;

-- Las tablas con id generado también necesitan su secuencia.
GRANT USAGE, SELECT ON SEQUENCE sgp_codigo_receta_id_seq, sgp_codigo_producto_id_seq, sgp_preparacion_id_seq,
  sgp_plan_dia_id_seq, sgp_plan_plato_id_seq, sgp_requisicion_id_seq,
  sgp_comparativo_dia_id_seq, sgp_comparativo_total_id_seq, sgp_costo_piso_techo_id_seq TO app_stock;
