-- V025: plan de producción diario del chef (2026-10-05).
--
-- * produccion_plan: las raciones a producir de cada plato de una minuta. Si no hay fila, valen las raciones de la minuta
--   (minuta_detalle.raciones). El chef las cambia a diario.
-- * produccion_plan_cambio: historial de solo lectura de cada cambio (anterior, nuevo, usuario, fecha de producción).
-- * Regla de la base (no solo de la pantalla):
--     - solo días desde 3 días atrás en adelante ((now() AT TIME ZONE 'America/Lima')::date - 3);
--     - el día no puede estar cerrado en cierre_diario;
--     - la minuta debe estar aprobada o cerrada (no en borrador);
--     - el usuario debe tener PRODUCCION_EDITAR en la operación (fn_tiene_permiso).
-- Tablas nuevas: produccion_plan, produccion_plan_cambio. No cambia ninguna columna existente.

-- ---------- Plan de producción ----------
CREATE TABLE produccion_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  minuta_detalle_id BIGINT NOT NULL,
  raciones_producir BIGINT NOT NULL CHECK (raciones_producir >= 0),
  usuario_id BIGINT NOT NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, minuta_detalle_id),
  FOREIGN KEY (empresa_id, minuta_detalle_id) REFERENCES minuta_detalle(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id)
);
CREATE INDEX ix_produccion_plan_usuario ON produccion_plan(empresa_id, usuario_id);

-- ---------- Historial de cambios (solo lectura) ----------
CREATE TABLE produccion_plan_cambio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  minuta_detalle_id BIGINT NOT NULL,
  fecha_produccion DATE NOT NULL,
  raciones_anterior BIGINT NOT NULL CHECK (raciones_anterior >= 0),
  raciones_nueva BIGINT NOT NULL CHECK (raciones_nueva >= 0),
  usuario_id BIGINT NOT NULL,
  ocurrido_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (empresa_id, minuta_detalle_id) REFERENCES minuta_detalle(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id)
);
CREATE INDEX ix_produccion_plan_cambio_detalle ON produccion_plan_cambio(empresa_id, minuta_detalle_id);
CREATE INDEX ix_produccion_plan_cambio_usuario ON produccion_plan_cambio(empresa_id, usuario_id);

-- ---------- Reglas ----------
CREATE FUNCTION fn_proteger_produccion_plan() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_fecha DATE;
  v_operacion BIGINT;
  v_estado TEXT;
BEGIN
  SELECT m.fecha, os.operacion_id, m.estado
    INTO v_fecha, v_operacion, v_estado
    FROM minuta_detalle md
    JOIN minuta m ON m.empresa_id = md.empresa_id AND m.id = md.minuta_id
    JOIN operacion_servicio os ON os.empresa_id = m.empresa_id AND os.id = m.operacion_servicio_id
   WHERE md.empresa_id = NEW.empresa_id AND md.id = NEW.minuta_detalle_id;

  IF v_fecha IS NULL THEN
    RAISE EXCEPTION 'DATO_INVALIDO: el plato de la minuta no existe';
  END IF;
  IF fn_usuario_actual() IS NOT NULL AND NOT fn_tiene_permiso('PRODUCCION_EDITAR', v_operacion) THEN
    RAISE EXCEPTION 'SIN_PERMISO: no puede cambiar la produccion de esta operacion';
  END IF;
  IF v_fecha < (now() AT TIME ZONE 'America/Lima')::date - 3 THEN
    RAISE EXCEPTION 'FUERA_DE_VENTANA: solo se cambia la produccion desde 3 dias atras en adelante';
  END IF;
  IF v_estado = 'borrador' THEN
    RAISE EXCEPTION 'MINUTA_EN_BORRADOR: la minuta todavia no esta aprobada';
  END IF;
  IF EXISTS (SELECT 1 FROM cierre_diario c WHERE c.empresa_id = NEW.empresa_id AND c.operacion_id = v_operacion
                                              AND c.fecha = v_fecha AND c.estado = 'cerrado') THEN
    RAISE EXCEPTION 'DIA_CERRADO: el dia ya esta cerrado; no se cambia la produccion';
  END IF;
  NEW.actualizado_en := now();
  NEW.usuario_id := COALESCE(fn_usuario_actual(), NEW.usuario_id);
  RETURN NEW;
END $$;
CREATE TRIGGER proteger_produccion_plan BEFORE INSERT OR UPDATE ON produccion_plan
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_produccion_plan();

CREATE FUNCTION fn_registrar_cambio_produccion() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_fecha DATE;
  v_raciones_minuta BIGINT;
BEGIN
  SELECT m.fecha, md.raciones INTO v_fecha, v_raciones_minuta
    FROM minuta_detalle md JOIN minuta m ON m.empresa_id = md.empresa_id AND m.id = md.minuta_id
   WHERE md.empresa_id = NEW.empresa_id AND md.id = NEW.minuta_detalle_id;
  INSERT INTO produccion_plan_cambio(empresa_id, minuta_detalle_id, fecha_produccion, raciones_anterior, raciones_nueva, usuario_id)
  VALUES (NEW.empresa_id, NEW.minuta_detalle_id, v_fecha,
          COALESCE(CASE WHEN TG_OP = 'UPDATE' THEN OLD.raciones_producir END, v_raciones_minuta),
          NEW.raciones_producir, NEW.usuario_id);
  RETURN NULL;
END $$;
CREATE TRIGGER registrar_cambio_produccion AFTER INSERT OR UPDATE ON produccion_plan
  FOR EACH ROW EXECUTE FUNCTION fn_registrar_cambio_produccion();

CREATE FUNCTION fn_historial_produccion_inmutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'HISTORIAL_INMUTABLE: el historial de produccion no se cambia ni se borra';
END $$;
CREATE TRIGGER historial_produccion_inmutable BEFORE UPDATE OR DELETE ON produccion_plan_cambio
  FOR EACH ROW EXECUTE FUNCTION fn_historial_produccion_inmutable();

-- ---------- Permisos, RLS y auditoría ----------
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['produccion_plan', 'produccion_plan_cambio'] LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO app_stock', t);
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %I_id_seq TO app_stock', t);
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY aislamiento_empresa ON %I FOR ALL TO app_stock
                      USING (empresa_id = fn_empresa_actual()) WITH CHECK (empresa_id = fn_empresa_actual())', t);
    EXECUTE format('CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON %I
                      FOR EACH ROW EXECUTE FUNCTION fn_auditar()', t);
  END LOOP;
END $$;
