-- V026: tablas que muestran las pantallas del SGP (capturas del 2026-10-02 al 2026-10-05, datos/sgp_pantallas/).
--
-- Solo se agrega lo que las capturas muestran con claridad; lo que no se ve (valores, fórmulas, significado de una sigla)
-- queda anotado en docs/TABLAS_SGP_VS_BASE.md y NO se inventa aquí.
--
-- Receta (pantalla "Receta", capturas 05-08, 10, 33)
--   * categoria_dietetica y tipo_plato (con jerarquía: "SALSAS / ALCUZAS / ISLAS\ALCUZAS", "GUARNICIONES\OTROS").
--   * receta: nombre de fantasía, categoría dietética y tipo de plato.
--   * receta_ingrediente (= detalle PATRÓN): %aprovechamiento y %ajuste de cocción.
--   * receta_ingrediente_ambito: detalle LOCAL (por operación) y detalle por RÉGIMEN (pestañas "Detalle Receta Local" y
--     "Detalle Receta x Regimen"). Igual que el patrón, solo se cambia con la versión en borrador.
--   * nutriente y producto_nutriente: aporte nutricional (pantalla Receta, "Aporte Planificación Teórica").
--     Base de la composición: por 100 g de parte comestible (la lista de nutrientes del SGP coincide con la de las
--     tablas peruanas de composición de alimentos). No se cargan valores: los archivos recibidos no traen nutrientes.
-- Planificación
--   * planificacion_mes_estado: "Histórico Planificación Teórica/Real" (Abierto/Cerrado por servicio y mes).
-- Control de raciones, venta y cafetería (capturas 47-52)
--   * control_racion y control_racion_dia: raciones por cliente, personal, producidas y mermas, y el día facturable.
--   * forma_pago y venta_servicio_dia: "Venta Servicio Contado" (importe por día, servicio, cliente y forma de pago).
--   * venta_cafeteria y venta_cafeteria_detalle: "Registro de Venta Cafetería".
-- Compras y traspasos (capturas 01, 16-18, 35-37, 58-59)
--   * proveedor: dirección y fax. pedido_compra: código del SGP, contacto, correo y periodo.
--   * recepcion: modalidad (CFC / FOFI), folio, glosa, fletes y monto exento.
--   * traspaso_documento y traspaso_linea: guía de remisión, placa, documento y contrato de origen, cantidad recibida.
-- Producción y operación
--   * documento_stock.fecha_produccion y documento_stock_detalle.cantidad_planificada_u6 (salida a producción:
--     "Cant. Planif." contra "Cant. Realizada"). operacion.codigo_optimum.
-- Reglas en la base (no solo en la pantalla): el día cerrado bloquea control de raciones y venta del día; un detalle de receta
-- aprobada no se cambia; los permisos se validan con fn_tiene_permiso.

-- ---------- Catálogos de receta ----------
CREATE TABLE categoria_dietetica (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  codigo TEXT NOT NULL CHECK (btrim(codigo) <> ''),
  nombre TEXT NOT NULL CHECK (btrim(nombre) <> ''),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, codigo)
);

CREATE TABLE tipo_plato (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  codigo TEXT NOT NULL CHECK (btrim(codigo) <> ''),
  nombre TEXT NOT NULL CHECK (btrim(nombre) <> ''),
  padre_id BIGINT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, codigo),
  FOREIGN KEY (empresa_id, padre_id) REFERENCES tipo_plato(empresa_id, id),
  CHECK (padre_id IS NULL OR padre_id <> id)
);
CREATE INDEX ix_tipo_plato_padre ON tipo_plato(empresa_id, padre_id);

ALTER TABLE receta
  ADD COLUMN nombre_fantasia TEXT CHECK (nombre_fantasia IS NULL OR btrim(nombre_fantasia) <> ''),
  ADD COLUMN categoria_dietetica_id BIGINT,
  ADD COLUMN tipo_plato_id BIGINT,
  ADD FOREIGN KEY (empresa_id, categoria_dietetica_id) REFERENCES categoria_dietetica(empresa_id, id),
  ADD FOREIGN KEY (empresa_id, tipo_plato_id) REFERENCES tipo_plato(empresa_id, id);
CREATE INDEX ix_receta_categoria_dietetica ON receta(empresa_id, categoria_dietetica_id);
CREATE INDEX ix_receta_tipo_plato ON receta(empresa_id, tipo_plato_id);

-- %Aprov. y %A.Coc. de la grilla de ingredientes; en puntos base (100 % = 10000). NULL = no informado.
ALTER TABLE receta_ingrediente
  ADD COLUMN pct_aprovechamiento_bp BIGINT CHECK (pct_aprovechamiento_bp IS NULL OR pct_aprovechamiento_bp BETWEEN 0 AND 100000),
  ADD COLUMN pct_ajuste_coccion_bp BIGINT CHECK (pct_ajuste_coccion_bp IS NULL OR pct_ajuste_coccion_bp BETWEEN 0 AND 100000);

-- ---------- Detalle de receta Local y por Régimen ----------
CREATE TABLE receta_ingrediente_ambito (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  receta_version_id BIGINT NOT NULL,
  ambito TEXT NOT NULL CHECK (ambito IN ('local', 'regimen')),
  operacion_id BIGINT,
  regimen_id BIGINT,
  producto_base_id BIGINT NOT NULL,
  cantidad_base_bruta_u6 BIGINT NOT NULL CHECK (cantidad_base_bruta_u6 > 0),
  pct_aprovechamiento_bp BIGINT CHECK (pct_aprovechamiento_bp IS NULL OR pct_aprovechamiento_bp BETWEEN 0 AND 100000),
  pct_ajuste_coccion_bp BIGINT CHECK (pct_ajuste_coccion_bp IS NULL OR pct_ajuste_coccion_bp BETWEEN 0 AND 100000),
  orden BIGINT NOT NULL DEFAULT 0,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE NULLS NOT DISTINCT (empresa_id, receta_version_id, ambito, operacion_id, regimen_id, producto_base_id),
  FOREIGN KEY (empresa_id, receta_version_id) REFERENCES receta_version(empresa_id, id),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id),
  FOREIGN KEY (empresa_id, regimen_id) REFERENCES regimen(empresa_id, id),
  FOREIGN KEY (empresa_id, producto_base_id) REFERENCES producto_base(empresa_id, id),
  CHECK ((ambito = 'local' AND operacion_id IS NOT NULL AND regimen_id IS NULL)
      OR (ambito = 'regimen' AND regimen_id IS NOT NULL))
);
CREATE INDEX ix_receta_ingrediente_ambito_version ON receta_ingrediente_ambito(empresa_id, receta_version_id);
CREATE INDEX ix_receta_ingrediente_ambito_operacion ON receta_ingrediente_ambito(empresa_id, operacion_id);
CREATE INDEX ix_receta_ingrediente_ambito_regimen ON receta_ingrediente_ambito(empresa_id, regimen_id);
CREATE INDEX ix_receta_ingrediente_ambito_producto ON receta_ingrediente_ambito(empresa_id, producto_base_id);

CREATE FUNCTION fn_proteger_ingrediente_ambito() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_estado TEXT;
BEGIN
  IF TG_OP <> 'INSERT' THEN
    SELECT estado INTO v_estado FROM receta_version WHERE empresa_id = OLD.empresa_id AND id = OLD.receta_version_id;
    IF v_estado <> 'borrador' THEN
      RAISE EXCEPTION 'RECETA_APROBADA: los ingredientes de una version % no se modifican', v_estado;
    END IF;
  END IF;
  IF TG_OP <> 'DELETE' THEN
    SELECT estado INTO v_estado FROM receta_version WHERE empresa_id = NEW.empresa_id AND id = NEW.receta_version_id;
    IF v_estado <> 'borrador' THEN
      RAISE EXCEPTION 'RECETA_APROBADA: los ingredientes de una version % no se modifican', v_estado;
    END IF;
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$;
CREATE TRIGGER proteger_ingrediente_ambito BEFORE INSERT OR UPDATE OR DELETE ON receta_ingrediente_ambito
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_ingrediente_ambito();

-- ---------- Nutrientes ----------
CREATE TABLE nutriente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  codigo TEXT NOT NULL CHECK (btrim(codigo) <> ''),
  nombre TEXT NOT NULL CHECK (btrim(nombre) <> ''),
  unidad TEXT NOT NULL CHECK (btrim(unidad) <> ''),
  orden BIGINT NOT NULL DEFAULT 0,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, codigo)
);

-- Composición de un ingrediente por 100 g de parte comestible (valor_100g_u6 = valor × 1 000 000).
CREATE TABLE producto_nutriente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  producto_base_id BIGINT NOT NULL,
  nutriente_id BIGINT NOT NULL,
  valor_100g_u6 BIGINT NOT NULL CHECK (valor_100g_u6 >= 0),
  fuente TEXT NOT NULL CHECK (btrim(fuente) <> ''),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, producto_base_id, nutriente_id),
  FOREIGN KEY (empresa_id, producto_base_id) REFERENCES producto_base(empresa_id, id),
  FOREIGN KEY (empresa_id, nutriente_id) REFERENCES nutriente(empresa_id, id)
);
CREATE INDEX ix_producto_nutriente_nutriente ON producto_nutriente(empresa_id, nutriente_id);

-- ---------- Estado mensual de la planificación ----------
CREATE TABLE planificacion_mes_estado (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_servicio_id BIGINT NOT NULL,
  anio BIGINT NOT NULL CHECK (anio BETWEEN 2000 AND 2200),
  mes BIGINT NOT NULL CHECK (mes BETWEEN 1 AND 12),
  tipo TEXT NOT NULL CHECK (tipo IN ('teorica', 'real')),
  estado TEXT NOT NULL DEFAULT 'abierto' CHECK (estado IN ('abierto', 'cerrado')),
  usuario_cierre_id BIGINT,
  fecha_cierre TIMESTAMPTZ,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, operacion_servicio_id, anio, mes, tipo),
  FOREIGN KEY (empresa_id, operacion_servicio_id) REFERENCES operacion_servicio(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_cierre_id) REFERENCES usuario(empresa_id, id),
  CHECK ((estado = 'cerrado') = (fecha_cierre IS NOT NULL))
);
CREATE INDEX ix_planificacion_mes_estado_servicio ON planificacion_mes_estado(empresa_id, operacion_servicio_id);
CREATE INDEX ix_planificacion_mes_estado_usuario ON planificacion_mes_estado(empresa_id, usuario_cierre_id);

-- ---------- Control de raciones ----------
-- concepto: 'cliente' (una fila por cliente), 'personal', 'producidas' y las dos mermas de la pantalla (MER_DESCON y
-- MER_PRODUC, nombres tal como salen en el SGP; su significado exacto está por confirmar).
CREATE TABLE control_racion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_servicio_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  concepto TEXT NOT NULL CHECK (concepto IN ('cliente', 'personal', 'producidas', 'mer_descon', 'mer_produc')),
  cliente_id BIGINT,
  raciones BIGINT NOT NULL CHECK (raciones >= 0),
  usuario_id BIGINT NOT NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE NULLS NOT DISTINCT (empresa_id, operacion_servicio_id, fecha, concepto, cliente_id),
  FOREIGN KEY (empresa_id, operacion_servicio_id) REFERENCES operacion_servicio(empresa_id, id),
  FOREIGN KEY (empresa_id, cliente_id) REFERENCES cliente(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id),
  CHECK ((concepto = 'cliente') = (cliente_id IS NOT NULL))
);
CREATE INDEX ix_control_racion_servicio_fecha ON control_racion(empresa_id, operacion_servicio_id, fecha);
CREATE INDEX ix_control_racion_cliente ON control_racion(empresa_id, cliente_id);
CREATE INDEX ix_control_racion_usuario ON control_racion(empresa_id, usuario_id);

-- Casilla "Facturable" de cada día del servicio.
CREATE TABLE control_racion_dia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_servicio_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  facturable BOOLEAN NOT NULL DEFAULT FALSE,
  usuario_id BIGINT NOT NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, operacion_servicio_id, fecha),
  FOREIGN KEY (empresa_id, operacion_servicio_id) REFERENCES operacion_servicio(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id)
);
CREATE INDEX ix_control_racion_dia_usuario ON control_racion_dia(empresa_id, usuario_id);

-- ---------- Venta servicio contado ----------
CREATE TABLE forma_pago (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  codigo TEXT NOT NULL CHECK (btrim(codigo) <> ''),
  nombre TEXT NOT NULL CHECK (btrim(nombre) <> ''),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, codigo)
);

CREATE TABLE venta_servicio_dia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_servicio_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  cliente_id BIGINT,
  forma_pago_id BIGINT NOT NULL,
  importe_u6 BIGINT NOT NULL CHECK (importe_u6 >= 0),
  usuario_id BIGINT NOT NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE NULLS NOT DISTINCT (empresa_id, operacion_servicio_id, fecha, cliente_id, forma_pago_id),
  FOREIGN KEY (empresa_id, operacion_servicio_id) REFERENCES operacion_servicio(empresa_id, id),
  FOREIGN KEY (empresa_id, cliente_id) REFERENCES cliente(empresa_id, id),
  FOREIGN KEY (empresa_id, forma_pago_id) REFERENCES forma_pago(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id)
);
CREATE INDEX ix_venta_servicio_dia_servicio_fecha ON venta_servicio_dia(empresa_id, operacion_servicio_id, fecha);
CREATE INDEX ix_venta_servicio_dia_cliente ON venta_servicio_dia(empresa_id, cliente_id);
CREATE INDEX ix_venta_servicio_dia_forma_pago ON venta_servicio_dia(empresa_id, forma_pago_id);
CREATE INDEX ix_venta_servicio_dia_usuario ON venta_servicio_dia(empresa_id, usuario_id);

-- ---------- Venta cafetería ----------
CREATE TABLE venta_cafeteria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  almacen_id BIGINT NOT NULL,
  fecha DATE NOT NULL,
  cliente_id BIGINT,
  centro_costo TEXT CHECK (centro_costo IS NULL OR btrim(centro_costo) <> ''),
  documento_stock_id BIGINT,
  usuario_id BIGINT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  FOREIGN KEY (empresa_id, almacen_id) REFERENCES almacen(empresa_id, id),
  FOREIGN KEY (empresa_id, cliente_id) REFERENCES cliente(empresa_id, id),
  FOREIGN KEY (empresa_id, documento_stock_id) REFERENCES documento_stock(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id)
);
CREATE INDEX ix_venta_cafeteria_almacen_fecha ON venta_cafeteria(empresa_id, almacen_id, fecha);
CREATE INDEX ix_venta_cafeteria_cliente ON venta_cafeteria(empresa_id, cliente_id);
CREATE INDEX ix_venta_cafeteria_documento ON venta_cafeteria(empresa_id, documento_stock_id);
CREATE INDEX ix_venta_cafeteria_usuario ON venta_cafeteria(empresa_id, usuario_id);

CREATE TABLE venta_cafeteria_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  venta_id BIGINT NOT NULL,
  variante_id BIGINT NOT NULL,
  cantidad_base_u6 BIGINT NOT NULL CHECK (cantidad_base_u6 > 0),
  precio_venta_u6 BIGINT NOT NULL CHECK (precio_venta_u6 >= 0),
  tipo_pago TEXT CHECK (tipo_pago IS NULL OR btrim(tipo_pago) <> ''),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  FOREIGN KEY (empresa_id, venta_id) REFERENCES venta_cafeteria(empresa_id, id),
  FOREIGN KEY (empresa_id, variante_id) REFERENCES variante_producto(empresa_id, id)
);
CREATE INDEX ix_venta_cafeteria_detalle_venta ON venta_cafeteria_detalle(empresa_id, venta_id);
CREATE INDEX ix_venta_cafeteria_detalle_variante ON venta_cafeteria_detalle(empresa_id, variante_id);

-- ---------- Día cerrado y permisos (control de raciones y venta del día) ----------
CREATE FUNCTION fn_proteger_dia_operativo() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_operacion BIGINT;
  v_fila RECORD;
BEGIN
  v_fila := CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
  SELECT os.operacion_id INTO v_operacion
    FROM operacion_servicio os WHERE os.empresa_id = v_fila.empresa_id AND os.id = v_fila.operacion_servicio_id;
  IF v_operacion IS NULL THEN
    RAISE EXCEPTION 'DATO_INVALIDO: el servicio de la operacion no existe';
  END IF;
  IF fn_usuario_actual() IS NOT NULL AND NOT fn_tiene_permiso(
       CASE WHEN TG_TABLE_NAME = 'venta_servicio_dia' THEN 'CIERRE_EJECUTAR' ELSE 'PRODUCCION_EDITAR' END, v_operacion) THEN
    RAISE EXCEPTION 'SIN_PERMISO: no puede cambiar este dato en esta operacion';
  END IF;
  IF EXISTS (SELECT 1 FROM cierre_diario c WHERE c.empresa_id = v_fila.empresa_id AND c.operacion_id = v_operacion
                                              AND c.fecha = v_fila.fecha AND c.estado = 'cerrado') THEN
    RAISE EXCEPTION 'DIA_CERRADO: el dia % ya esta cerrado', v_fila.fecha;
  END IF;
  IF TG_OP <> 'DELETE' THEN
    NEW.actualizado_en := now();
    NEW.usuario_id := COALESCE(fn_usuario_actual(), NEW.usuario_id);
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$;
CREATE TRIGGER proteger_dia_operativo BEFORE INSERT OR UPDATE OR DELETE ON control_racion
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_dia_operativo();
CREATE TRIGGER proteger_dia_operativo BEFORE INSERT OR UPDATE OR DELETE ON control_racion_dia
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_dia_operativo();
CREATE TRIGGER proteger_dia_operativo BEFORE INSERT OR UPDATE OR DELETE ON venta_servicio_dia
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_dia_operativo();

-- ---------- Compras: proveedor, pedido y documento proveedor ----------
ALTER TABLE proveedor
  ADD COLUMN direccion TEXT CHECK (direccion IS NULL OR btrim(direccion) <> ''),
  ADD COLUMN fax TEXT CHECK (fax IS NULL OR btrim(fax) <> '');

-- codigo_sgp: código de la tanda de pedidos que imprime el SGP (p. ej. LCL-06695-092026-ORCOPA_1); lo repiten todos los
-- proveedores de la misma tanda, por eso no es único.
ALTER TABLE pedido_compra
  ADD COLUMN codigo_sgp TEXT CHECK (codigo_sgp IS NULL OR btrim(codigo_sgp) <> ''),
  ADD COLUMN persona_contacto TEXT CHECK (persona_contacto IS NULL OR btrim(persona_contacto) <> ''),
  ADD COLUMN correo_destino TEXT CHECK (correo_destino IS NULL OR btrim(correo_destino) <> ''),
  ADD COLUMN periodo_desde DATE,
  ADD COLUMN periodo_hasta DATE,
  ADD CONSTRAINT pedido_compra_periodo_check CHECK (periodo_desde IS NULL OR periodo_hasta IS NULL OR periodo_hasta >= periodo_desde);

-- modalidad_sgp: opción "Tipo de Operación" de la pantalla Documento Proveedor (CFC o FOFI) con su folio.
ALTER TABLE recepcion
  ADD COLUMN modalidad_sgp TEXT CHECK (modalidad_sgp IS NULL OR modalidad_sgp IN ('CFC', 'FOFI')),
  ADD COLUMN folio BIGINT CHECK (folio IS NULL OR folio >= 0),
  ADD COLUMN glosa TEXT CHECK (glosa IS NULL OR btrim(glosa) <> ''),
  ADD COLUMN fletes_u6 BIGINT CHECK (fletes_u6 IS NULL OR fletes_u6 >= 0),
  ADD COLUMN exento_u6 BIGINT CHECK (exento_u6 IS NULL OR exento_u6 >= 0);

-- ---------- Traspasos (entre contratos, CD, bodegas) ----------
CREATE TABLE traspaso_documento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  documento_stock_id BIGINT NOT NULL,
  modalidad TEXT NOT NULL CHECK (modalidad IN ('contrato', 'cd', 'bodega', 'alm_remoto')),
  folio BIGINT CHECK (folio IS NULL OR folio >= 0),
  contrato_origen TEXT CHECK (contrato_origen IS NULL OR btrim(contrato_origen) <> ''),
  numero_documento_origen TEXT CHECK (numero_documento_origen IS NULL OR btrim(numero_documento_origen) <> ''),
  fecha_origen DATE,
  guia_remision TEXT CHECK (guia_remision IS NULL OR btrim(guia_remision) <> ''),
  orden_pedido TEXT CHECK (orden_pedido IS NULL OR btrim(orden_pedido) <> ''),
  placa_camion TEXT CHECK (placa_camion IS NULL OR btrim(placa_camion) <> ''),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, documento_stock_id),
  FOREIGN KEY (empresa_id, documento_stock_id) REFERENCES documento_stock(empresa_id, id)
);

-- Cantidad recibida de una línea del traspaso (la columna "Cant.Recibida" puede diferir de "Cantidad").
CREATE TABLE traspaso_linea (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  documento_detalle_id BIGINT NOT NULL,
  cantidad_recibida_base_u6 BIGINT NOT NULL CHECK (cantidad_recibida_base_u6 >= 0),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, documento_detalle_id),
  FOREIGN KEY (empresa_id, documento_detalle_id) REFERENCES documento_stock_detalle(empresa_id, id)
);

-- ---------- Salida a producción y operación ----------
ALTER TABLE documento_stock ADD COLUMN fecha_produccion DATE;
ALTER TABLE documento_stock_detalle
  ADD COLUMN cantidad_planificada_u6 BIGINT CHECK (cantidad_planificada_u6 IS NULL OR cantidad_planificada_u6 >= 0);
ALTER TABLE operacion
  ADD COLUMN codigo_optimum TEXT CHECK (codigo_optimum IS NULL OR btrim(codigo_optimum) <> '');

-- ---------- Permisos, RLS y auditoría de las tablas nuevas ----------
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['categoria_dietetica', 'tipo_plato', 'receta_ingrediente_ambito', 'nutriente', 'producto_nutriente',
                           'planificacion_mes_estado', 'control_racion', 'control_racion_dia', 'forma_pago', 'venta_servicio_dia',
                           'venta_cafeteria', 'venta_cafeteria_detalle', 'traspaso_documento', 'traspaso_linea'] LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO app_stock', t);
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %I_id_seq TO app_stock', t);
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY aislamiento_empresa ON %I FOR ALL TO app_stock
                      USING (empresa_id = fn_empresa_actual()) WITH CHECK (empresa_id = fn_empresa_actual())', t);
    EXECUTE format('CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON %I
                      FOR EACH ROW EXECUTE FUNCTION fn_auditar()', t);
  END LOOP;
END $$;
