-- V024: solicitud de devolución desde cocina (pedido del usuario, 2026-10-05).
--
-- El chef pide devolver parte de una entrega a producción; el almacenero la atiende y recién entonces hay movimiento
-- de stock (devolución de producción, al costo histórico de la entrega). La cocina no toca el stock.
-- * Nace en 'pendiente'. Solo cambia de pendiente a atendida (con su documento de devolución) o anulada.
-- * La cantidad nunca supera lo entregado menos lo ya devuelto: se valida al pedir y otra vez al atender.
-- Con la conexión del propietario o del instalador (sin app.usuario_id) las reglas de permiso no aplican.

CREATE TABLE devolucion_solicitud (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  almacen_id BIGINT NOT NULL,
  documento_origen_id BIGINT NOT NULL,            -- la entrega a producción que se devuelve
  variante_id BIGINT NOT NULL,
  cantidad_base_u6 BIGINT NOT NULL CHECK (cantidad_base_u6 > 0),
  motivo TEXT,
  estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'atendida', 'anulada')),
  solicitado_por BIGINT NOT NULL,
  solicitado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  documento_devolucion_id BIGINT,
  atendido_por BIGINT,
  atendido_en TIMESTAMPTZ,
  UNIQUE(empresa_id, id),
  FOREIGN KEY (empresa_id, almacen_id) REFERENCES almacen(empresa_id, id),
  FOREIGN KEY (empresa_id, documento_origen_id) REFERENCES documento_stock(empresa_id, id),
  FOREIGN KEY (empresa_id, variante_id) REFERENCES variante_producto(empresa_id, id),
  FOREIGN KEY (empresa_id, solicitado_por) REFERENCES usuario(empresa_id, id),
  FOREIGN KEY (empresa_id, documento_devolucion_id) REFERENCES documento_stock(empresa_id, id),
  FOREIGN KEY (empresa_id, atendido_por) REFERENCES usuario(empresa_id, id),
  CHECK ((estado = 'atendida') = (documento_devolucion_id IS NOT NULL))
);
CREATE INDEX ix_devolucion_solicitud_almacen ON devolucion_solicitud(empresa_id, almacen_id, estado);
CREATE INDEX ix_devolucion_solicitud_origen ON devolucion_solicitud(empresa_id, documento_origen_id);
CREATE INDEX ix_devolucion_solicitud_variante ON devolucion_solicitud(empresa_id, variante_id);
CREATE INDEX ix_devolucion_solicitud_solicitado_por ON devolucion_solicitud(empresa_id, solicitado_por);
CREATE INDEX ix_devolucion_solicitud_atendido_por ON devolucion_solicitud(empresa_id, atendido_por) WHERE atendido_por IS NOT NULL;
CREATE INDEX ix_devolucion_solicitud_documento ON devolucion_solicitud(empresa_id, documento_devolucion_id) WHERE documento_devolucion_id IS NOT NULL;

CREATE FUNCTION fn_proteger_devolucion_solicitud() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'DEVOLUCION_SOLICITUD: una solicitud no se elimina; se anula';
  END IF;
  IF TG_OP = 'INSERT' THEN
    IF NEW.estado <> 'pendiente' THEN
      RAISE EXCEPTION 'DEVOLUCION_SOLICITUD: toda solicitud nace pendiente';
    END IF;
    RETURN NEW;
  END IF;
  IF OLD.estado <> 'pendiente' THEN
    RAISE EXCEPTION 'DEVOLUCION_SOLICITUD: la solicitud esta % y no se modifica', OLD.estado;
  END IF;
  IF (NEW.almacen_id, NEW.documento_origen_id, NEW.variante_id, NEW.cantidad_base_u6, NEW.solicitado_por)
     IS DISTINCT FROM (OLD.almacen_id, OLD.documento_origen_id, OLD.variante_id, OLD.cantidad_base_u6, OLD.solicitado_por) THEN
    RAISE EXCEPTION 'DATO_INVALIDO: los datos de la solicitud no se cambian; cree otra';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER proteger_devolucion_solicitud BEFORE INSERT OR UPDATE OR DELETE ON devolucion_solicitud
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_devolucion_solicitud();

GRANT SELECT, INSERT, UPDATE ON devolucion_solicitud TO app_stock;
GRANT USAGE, SELECT ON SEQUENCE devolucion_solicitud_id_seq TO app_stock;
ALTER TABLE devolucion_solicitud ENABLE ROW LEVEL SECURITY;
CREATE POLICY aislamiento_empresa ON devolucion_solicitud FOR ALL TO app_stock
  USING (empresa_id = fn_empresa_actual()) WITH CHECK (empresa_id = fn_empresa_actual());
CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON devolucion_solicitud FOR EACH ROW EXECUTE FUNCTION fn_auditar();
