-- V026: raciones operativas del plan del chef (especificación 02 y 06: "raciones teóricas frente a operativas").
--
-- * El plan teórico y su snapshot aprobado no se tocan (minuta_detalle sigue protegida). El ajuste del chef vive aquí,
--   un registro por plato: raciones operativas, motivo, quién y cuándo.
-- * Regla por defecto (documentada en docs/CHECKLIST.md): el ajuste se permite en minutas aprobadas y solo mientras no
--   haya un requerimiento atendido de esa minuta. Después del despacho, el cambio se pide como adicional.
-- * Sin ajuste, las raciones operativas son las teóricas.
-- Con la conexión del propietario o del instalador las reglas de permiso no aplican.

CREATE TABLE minuta_ajuste_operativo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  minuta_detalle_id BIGINT NOT NULL,
  raciones_operativas BIGINT NOT NULL CHECK (raciones_operativas >= 0),
  motivo TEXT NOT NULL CHECK (btrim(motivo) <> ''),
  usuario_id BIGINT NOT NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, id),
  UNIQUE (empresa_id, minuta_detalle_id),
  FOREIGN KEY (empresa_id, minuta_detalle_id) REFERENCES minuta_detalle(empresa_id, id),
  FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuario(empresa_id, id)
);
CREATE INDEX ix_minuta_ajuste_operativo_usuario ON minuta_ajuste_operativo(empresa_id, usuario_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON minuta_ajuste_operativo TO app_stock;
GRANT USAGE, SELECT ON SEQUENCE minuta_ajuste_operativo_id_seq TO app_stock;
ALTER TABLE minuta_ajuste_operativo ENABLE ROW LEVEL SECURITY;
CREATE POLICY aislamiento_empresa ON minuta_ajuste_operativo FOR ALL TO app_stock
  USING (empresa_id = fn_empresa_actual()) WITH CHECK (empresa_id = fn_empresa_actual());
CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON minuta_ajuste_operativo FOR EACH ROW EXECUTE FUNCTION fn_auditar();
