-- V029: traspaso en dos pasos (tránsito), decisión del usuario (opción A).
--
-- Antes, un traspaso sacaba el stock del origen y lo ponía en el destino en la misma transacción. Ahora:
-- * Enviar: sale el stock del origen (documento traspaso_salida) y el traspaso nace 'enviado'. Mientras tanto, la
--   mercadería está en tránsito: no está en ningún almacén.
-- * Recibir: en el destino se crea el documento traspaso_entrada, por el mismo valor de la salida, y el traspaso pasa a
--   'recibido'. Es todo o nada: la recepción parcial queda para una versión posterior.
-- * Un traspaso enviado sin recibir bloquea el cierre del día en que se envió (ver ServicioCierres, TRANSITO_PENDIENTE).
-- Los traspasos anteriores a esta versión ya nacieron recibidos: se registran como 'recibido' con su entrada.
-- Nada se elimina y los datos del envío no cambian; solo la recepción modifica la fila (una vez).

CREATE TABLE traspaso_transito (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresa(id),
  operacion_id BIGINT NOT NULL,
  numero TEXT NOT NULL,                           -- correlativo TR (el mismo del traspaso)
  almacen_origen_id BIGINT NOT NULL,
  almacen_destino_id BIGINT NOT NULL,
  documento_salida_id BIGINT NOT NULL,
  fecha_envio DATE NOT NULL,
  valor_u6 BIGINT NOT NULL CHECK (valor_u6 >= 0),
  estado TEXT NOT NULL DEFAULT 'enviado' CHECK (estado IN ('enviado', 'recibido')),
  documento_entrada_id BIGINT,
  fecha_recepcion DATE,
  recibido_por BIGINT,
  UNIQUE(empresa_id, id),
  UNIQUE(empresa_id, documento_salida_id),
  FOREIGN KEY (empresa_id, operacion_id) REFERENCES operacion(empresa_id, id),
  FOREIGN KEY (empresa_id, almacen_origen_id) REFERENCES almacen(empresa_id, id),
  FOREIGN KEY (empresa_id, almacen_destino_id) REFERENCES almacen(empresa_id, id),
  FOREIGN KEY (empresa_id, documento_salida_id) REFERENCES documento_stock(empresa_id, id),
  FOREIGN KEY (empresa_id, documento_entrada_id) REFERENCES documento_stock(empresa_id, id),
  FOREIGN KEY (empresa_id, recibido_por) REFERENCES usuario(empresa_id, id),
  CHECK (almacen_origen_id <> almacen_destino_id),
  CHECK ((estado = 'recibido') = (documento_entrada_id IS NOT NULL AND fecha_recepcion IS NOT NULL AND recibido_por IS NOT NULL))
);
CREATE INDEX ix_traspaso_transito_operacion ON traspaso_transito(empresa_id, operacion_id, estado);
CREATE INDEX ix_traspaso_transito_origen ON traspaso_transito(empresa_id, almacen_origen_id);
CREATE INDEX ix_traspaso_transito_destino ON traspaso_transito(empresa_id, almacen_destino_id, estado);
CREATE INDEX ix_traspaso_transito_entrada ON traspaso_transito(empresa_id, documento_entrada_id) WHERE documento_entrada_id IS NOT NULL;
CREATE INDEX ix_traspaso_transito_recibido_por ON traspaso_transito(empresa_id, recibido_por) WHERE recibido_por IS NOT NULL;

CREATE FUNCTION fn_proteger_traspaso_transito() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'TRASPASO_TRANSITO: un traspaso no se elimina';
  END IF;
  IF TG_OP = 'INSERT' THEN
    IF NEW.estado <> 'enviado' THEN
      RAISE EXCEPTION 'TRASPASO_TRANSITO: todo traspaso nace enviado';
    END IF;
    RETURN NEW;
  END IF;
  IF OLD.estado <> 'enviado' THEN
    RAISE EXCEPTION 'TRASPASO_TRANSITO: el traspaso ya esta recibido y no se modifica';
  END IF;
  IF (NEW.operacion_id, NEW.numero, NEW.almacen_origen_id, NEW.almacen_destino_id, NEW.documento_salida_id, NEW.fecha_envio, NEW.valor_u6)
     IS DISTINCT FROM (OLD.operacion_id, OLD.numero, OLD.almacen_origen_id, OLD.almacen_destino_id, OLD.documento_salida_id, OLD.fecha_envio, OLD.valor_u6) THEN
    RAISE EXCEPTION 'DATO_INVALIDO: los datos del envio no se cambian';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER proteger_traspaso_transito BEFORE INSERT OR UPDATE OR DELETE ON traspaso_transito
  FOR EACH ROW EXECUTE FUNCTION fn_proteger_traspaso_transito();

GRANT SELECT, INSERT, UPDATE ON traspaso_transito TO app_stock;
GRANT USAGE, SELECT ON SEQUENCE traspaso_transito_id_seq TO app_stock;
ALTER TABLE traspaso_transito ENABLE ROW LEVEL SECURITY;
CREATE POLICY aislamiento_empresa ON traspaso_transito FOR ALL TO app_stock
  USING (empresa_id = fn_empresa_actual()) WITH CHECK (empresa_id = fn_empresa_actual());
CREATE TRIGGER auditar AFTER INSERT OR UPDATE OR DELETE ON traspaso_transito FOR EACH ROW EXECUTE FUNCTION fn_auditar();

-- Traspasos anteriores: ya estaban recibidos (la entrada se hizo en el mismo momento). Se registran para que el monitor
-- muestre el histórico y no queden como tránsitos abiertos.
ALTER TABLE traspaso_transito DISABLE TRIGGER proteger_traspaso_transito;   -- solo para esta copia: nacen ya recibidos
INSERT INTO traspaso_transito (empresa_id, operacion_id, numero, almacen_origen_id, almacen_destino_id, documento_salida_id,
                               fecha_envio, valor_u6, estado, documento_entrada_id, fecha_recepcion, recibido_por)
SELECT s.empresa_id, a.operacion_id, left(s.numero, length(s.numero) - 2), s.almacen_id, s.almacen_destino_id, s.id,
       s.fecha, COALESCE((SELECT sum(l.valor_u6) FROM documento_stock_detalle l WHERE l.documento_id = s.id), 0), 'recibido',
       e.id, e.fecha, COALESCE(e.usuario_id, s.usuario_id)
FROM documento_stock s
JOIN almacen a ON a.empresa_id = s.empresa_id AND a.id = s.almacen_id
JOIN documento_stock e ON e.empresa_id = s.empresa_id AND e.documento_origen_id = s.id AND e.tipo = 'traspaso_entrada'
WHERE s.tipo = 'traspaso_salida';
ALTER TABLE traspaso_transito ENABLE TRIGGER proteger_traspaso_transito;
